= Struttura del mondo

== Creazione:

All'inizio i 2 piani erano uniti, l'energia e la materia erano uniti. Grandi concentrazioni di energia hanno iniziato a spostarsi, e ad "agire" da sole. Questo ha portato alla nascita degli elementi che hanno iniziato a separarsi, ed a manifestarsi sulla materia. Questa separazione ha portato ad uno scisma tra i due piani, separando il materiale dal piano dell'energia. Il mondo è stato creato da queste manifestazioni di energia, che col tempo hanno iniziato a sviluppare una "coscenza" anche se non si tratta di una vera e propria coscenza di se. Hanno poi iniziato a creare la vita, prima sottoforma di piante, poi animali, fino ad arrivare a creare i draghi, i quali sono stati creati come rappresentazioni degli elementi, seppur in forma molto più ridotta rispetto ai loro creatori. I semidei, vedendo la bellezza delle loro creazioni, hanno scelto di manifestarsi ad essi nella loro forma. Solo allora, da agglomerati di energia pura, e senza forma sono passati ad essere i grandi dragoni. I draghi vivevano liberi ed incontrastati ovunque nel mondo, ma riconoscevano nell'isola di Valentar la loro casa, dove risiedevano i 9 semidei. Col tempo poi altre forme di vita hanno iniziato a svilupparsi, con l'aiuto dei grandi dragoni, soprattutto Londrun. Ha reso possibile la nascita e lo sviluppo delle prime civiltà: gli elfi alti e gli umani. I primi, creati da Londrun, sono stati poi benedetti da Drogshul con una connessione al piano astrale particolarmente accentuata. Gli umani invece, inizialmente erano liberi, visti dagli elfi come poco più che animali selvaggi e violenti. Col passare dei secoli nuove razze hanno iniziato a spuntare, come i nani, benedetti da Jotraanviir con una conoscenza profonda della roccia e dei metalli, e gli gnomi, prediletti da Drogshul, dotati di una straordinaria intelligenza 

L'universo è diviso in 2 parti: 

* Piano Materiale
* Piano Astrale

I 2 piani sono separati ma allo stesso tempo collegati. Sono divisi da una "barriera", e collegati da portali. Inoltre il collegamento tra i piani varia in forza a seconda del luogo. In cima alla montagna ai confini del Regno di Balir ad esempio, risiede Avyumakra, il grande dragone bianco, signore dell'inverno, e la montagna stessa è infestata da elementali di ghiaccio. Nei pilastri invece, dopo la catastrofe che ha spazzato via la civiltà, la barriera che separa i due mondi è spezzata, e la sua rottura ha portato al riversamento di energia dal piano astrale in quello materiale, causando varie mutazioni ed epidemie; è dove buona parte dei mezzosangue vivono, assieme agli aviani.

== Piano Materiale

Il piano dove vivono quasi tutti i mortali. Composto da 5 continenti principali: Valentar, Talenalia, Gorlanos, Ar-hadda, Vallea.

* Valentar
** Il continente dove per prima è comparsa la vita intelligente, sottoforma di draghi. Composto da un'unica isola ora è l'unico rifugio di molti draghi, nonché il loro principale cimitero, ed il centro del culto dei grandi dragoni.
* Vallea
** Vallea ospita perlopiù umani. La maggior parte del continente è territorio dell'Impero degli uomini, o di Adahimia. Il continente è diviso in 2 isole: Vallea, l'isola più grande, e l'isola volante di Arquel, che ospita l'omonima capitale imperiale.
* Shorlea
** Il continente composto da 4 isole, Talenalia, l'isola principale contesa tra barbari di Yas, il popolo di Balir ed il Matriarcato, Elelia, lo scudo del sud, occupato dalla Legione di Tilgan, Valelya, centro di studio religioso e magico del Matriarcato, e Marelia, terra perennemente spazzata da venti gelidi, dove si trova Yas.
* Ar-hadda
** Ar-hadda, comunemente noto come I Pilastri di Ar-hadda, o Pilastri, era un'unica isola, luogo d'origine della razza elfica. Dopo un'enorme catastrofe dovuta alla loro arroganza, l'isola è emersa dalle acque, e si è spaccata formando un arcipelago di fiordi e altopiani. Il continente ora è spazzato da costanti tempeste di pura energia magica, emanata da quella che era la capitale elfica, che ora prende il nome di Krater, ha mutato gli elfi, i loro schiavi umani e quasi tutte le creature che popolavano il continente, mutandole e generando gli abomini noti adesso come gli uomini-bestia e gli aviani.
* Gorlanos
** Gorlanos, oggi comunemente noto come Terre Libere del Nord Ovest è un piccolo continente, variegato, in cui 6 piccole fazioni si contendono la supremazia.

== Piano Astrale

Il piano astrale è un grande vuoto, privo di luce, dove l'energia e quindi la magia, scorre in flutti come fosse un fiume, è il dominio di dèi, demoni e guardiani, che si muovono come esseri di pura energia. Gli unici elementi "solidi" che occupano il piano astrale sono i viaggiatori che utilizzano il piano per spostarsi lungo grandi distanze, i vari portali che collegano parti del mondo, e le "ancore" dimensionali utilizzate come punto di riferimento per il viaggio: si tratta di strutture che esistono sia nel materiale che nell'astrale. Agiscono un po come fari, contornati dal riflesso astrale di tutti gli esseri viventi che popolano il mondo. Vi sono inoltre delle piccole enclave di elfi astrali, ed una loro città.

== Collegamento tra i 2 piani:

Il piano astrale, è una dimensione diversa da quella terrena, e tenuta in contatto con la stessa tramite distorsioni nel piano materiale, che permettono all'energia di scorrere da e verso il piano materiale. Le due distorsioni principali sono comparse con la catastrofe: il cratere dentro il quale si sviluppa la città di Krater è stato formato proprio a causa di un continuo riversarsi di energia astrale nel piano materiale. Quest'energia scorre nel mondo ed attraverso di esso, causando lievi mutazioni e permettendo l'uso della magia, quella rimasta continua a spostarsi e torna nel piano astrale dal dente di ghiaccio, la montagna ad est dell'isola di Talenalia. col tempo questo scorrere di magia ha trasformato quello che era un gruppo di colline relativamente basse nella montagna più alta del mondo. Oltre a questi due portali "naturali", vi sono numerosi modi di accedere al piano astrale, sviluppati nel tempo da vari maghi e studiosi di magia. Il piano astrale infatti consente di accorciare notevolmente le distanze ed i tempi di viaggio, ed ha favorito lo sviluppo tecnologico di molte nazioni. Uno dei modi principali è tramite portali fissi, situati nelle città principali, metodo utilizzato soprattutto in Adahimia, dove ogni capitale provinciale dell'impero è collegata alle altre. Altri modi, utilizzati soprattutto dai commercianti, è tramite veicoli. Vi sono infatti molti maghi che offrono i loro servizi per permettere a trasporti di vario genere (carri, aeromobili, autocarri ecc), di entrare, spostarsi ed uscire dal piano astrale alle giuste coordinate, e indenni. Questa forma di trasporto viene ottenuta aprendo un varco temporaneo nel piano materiale, e spostandosi nei flutti di energia del piano astrale seguendo le varie ancore astrali. Questa tecnica però non consente un trasporto preciso, ma permette di coprire grandi distanze in giorni o settimane invece che mesi, o addirittura anni, e con molti meno rischi.

== Sul tempo

Il tempo nel mondo scorre in modo particolare. Il pianeta ha un'orbita ellittica scentrata intorno ad un sistema binario, il che lo porta a compiere un giro completo in 4 anni. ogni ciclo di 4 anni

[cols="3", options="header"]
|===
^.^|Nome			^.^|Posizione				^.^|Nazione
^.^|Norlyn			^.^|Meridia					^.^|Regno libero del sottosuolo, TLDNO
^.^|Laria			^.^|Meridia					^.^|Impero di Meridia, TLDNO
^.^|Carelian		^.^|Meridia					^.^|Ribelli, TLDNO
^.^|Tedara			^.^|Arstelda				^.^|Città stato di Tedara, TLDNO
^.^|Ederla			^.^|Meridia					^.^|Ducato Vulic, TLDNO
^.^|Medor			^.^|Lunia					^.^|Gilda della Fenice / Confederazione Commerciale, TLDNO
^.^|Sernost			^.^|Vagra					^.^|Repubblica Scarlatta, TLDNO
^.^|Ethedan			^.^|Vagra					^.^|Repubblica Scarlatta, TLDNO
^.^|Vihr			^.^|Valentar				^.^|Valentar
^.^|Londaure		^.^|Valentar				^.^|Elfi Silvani
^.^|Krater			^.^|Pilastro di Krater		^.^|Pilastri di Ar-hadda
^.^|Yas				^.^|Marelia					^.^|Regno di Ignar
^.^|Balir			^.^|Talenalia				^.^|Regno di Balir
^.^|Garenia		 	^.^|Talenalia				^.^|Regno di Balir
^.^|Exeter			^.^|Talenalia				^.^|Regno di Balir
^.^|Opensha			^.^|Talenalia				^.^|Regno di Balir
^.^|Lingmell		^.^|Talenalia				^.^|Regno di Balir
^.^|Nuxvar 			^.^|Talenalia				^.^|Regno di Balir
^.^|Threlkeld		^.^|Talenalia				^.^|Regno di Balir
^.^|Hankala			^.^|Talenalia				^.^|Regno di Balir
^.^|Aynor			^.^|Talenalia				^.^|Regno di Balir
^.^|Fernsworth		^.^|Talenalia				^.^|Regno di Balir
^.^|Nantgarth		^.^|Talenalia				^.^|Regno di Balir
^.^|Blaena			^.^|Talenalia				^.^|Regno di Balir
^.^|Penshaw			^.^|Talenalia				^.^|Regno di Balir
^.^|Ilebur			^.^|Talenalia				^.^|Regno di Balir
^.^|Ar-Olmore 		^.^|Talenalia				^.^|Regno di Balir
^.^|Swindmore		^.^|Talenalia				^.^|Regno di Balir
^.^|Kaiven			^.^|Talenalia				^.^|Regno di Balir
^.^|Grilab			^.^|Talenalia				^.^|Regno di Balir
^.^|Olusien			^.^|Talenalia				^.^|Regno di Balir
^.^|Calibard		^.^|Talenalia				^.^|Regno di Balir
^.^|Urfao			^.^|Talenalia				^.^|Regno di Balir
^.^|Pimmalin		^.^|Talenalia				^.^|Regno di Balir
^.^|Amaril			^.^|Talenalia				^.^|Figlie di Talena
^.^|Harailin		^.^|Talenalia				^.^|Figlie di Talena
^.^|Casserin		^.^|Talenalia				^.^|Figlie di Talena
^.^|Nilnedell		^.^|Talenalia				^.^|Figlie di Talena
^.^|Isil Galas		^.^|Talenalia				^.^|Figlie di Talena
^.^|Colthyr			^.^|Talenalia				^.^|Figlie di Talena
^.^|Deloriamd		^.^|Talenalia				^.^|Figlie di Talena
^.^|Thrulith		^.^|Talenalia				^.^|Figlie di Talena
^.^|Niomir			^.^|Talenalia				^.^|Figlie di Talena
^.^|Shyrlond		^.^|Talenalia				^.^|Figlie di Talena
^.^|Sil Gandil		^.^|Talenalia				^.^|Figlie di Talena
^.^|Belil Gadien	^.^|Talenalia				^.^|Figlie di Talena
^.^|Ril Galia		^.^|Talenalia				^.^|Figlie di Talena
^.^|Muriand			^.^|Talenalia				^.^|Figlie di Talena
^.^|Pil Gand		^.^|Talenalia				^.^|Figlie di Talena
^.^|Moriand			^.^|Talenalia				^.^|Figlie di Talena
^.^|Erynior			^.^|Talenalia				^.^|Figlie di Talena
^.^|Daerist			^.^|Talenalia				^.^|Figlie di Talena
^.^|Annuithang		^.^|Talenalia				^.^|Figlie di Talena
^.^|Nydalla			^.^|Valelya					^.^|Figlie di Talena
^.^|Calaril			^.^|Valelya					^.^|Figlie di Talena
^.^|Anorion			^.^|Valelya					^.^|Figlie di Talena
^.^|Veomyr			^.^|Elelia					^.^|Legione di Tilgan
^.^|Greyshel		^.^|Elelia					^.^|Legione di Tilgan
^.^|Damerel			^.^|Elelia					^.^|Legione di Tilgan
^.^|Vanniste		^.^|Elelia					^.^|Legione di Tilgan
^.^|Halvik			^.^|Elelia					^.^|Legione di Tilgan
^.^|Walden			^.^|Elelia					^.^|Legione di Tilgan
^.^|Estgal			^.^|Elelia					^.^|Legione di Tilgan
^.^|Asmont			^.^|Elelia					^.^|Legione di Tilgan
^.^|Pinepoint		^.^|Elelia					^.^|Legione di Tilgan
^.^|Brassfort		^.^|Elelia					^.^|Legione di Tilgan
^.^|Stillgarde		^.^|Elelia					^.^|Legione di Tilgan
^.^|Rachdale		^.^|Elelia					^.^|Legione di Tilgan
^.^|Coveford		^.^|Elelia					^.^|Legione di Tilgan
^.^|Tromwern		^.^|Elelia					^.^|Legione di Tilgan
^.^|Wildereach		^.^|Elelia					^.^|Legione di Tilgan
^.^|Gearsberg		^.^|Elelia					^.^|Legione di Tilgan
^.^|Kalgara			^.^|Elelia					^.^|Legione di Tilgan
^.^|Bralen			^.^|Vallea					^.^|Impero di Adahim
^.^|Bralenfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Asoar			^.^|Vallea					^.^|Impero di Adahim
^.^|Sedrim			^.^|Vallea					^.^|Impero di Adahim
^.^|Sedrimfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Artosk			^.^|Vallea					^.^|Impero di Adahim
^.^|Shaystorn		^.^|Vallea					^.^|Impero di Adahim
^.^|Shayfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Grilming		^.^|Vallea					^.^|Impero di Adahim
^.^|Winglark		^.^|Vallea					^.^|Impero di Adahim
^.^|Conacon			^.^|Vallea					^.^|Impero di Adahim
^.^|Arquel			^.^|Vallea					^.^|Impero di Adahim
^.^|Caras Astra		^.^|Piano Astrale			^.^|Enclave astrale di Caras Astra
|===