= Sulla magia

La magia, in entrambi i piani consiste principalmente in manipolazione dell'energia. Nel piano materiale, prima della catastrofe, la magia era disponibile principalmente in elfi e draghi, ed in quantità relativamente limitate alle altre razze senzienti. Questo in quanto nel piano materiale l'energia astrale era molto dispersa nel mondo. Elfi e dragoni invece avevano un collegamento diretto con il piano astrale, e potevano attingervi in qualsiasi momento. Con la catastrofe, l'energia astrale si è diffusa nel mondo, consentendo alle altre razze i sviluppare altri tipi di magia.

== Magia Distaccata

La prima forma di magia, quella praticata originariamente da elfi e dragoni, è una forma di magia che consente all'individuo di attingere all'energia astrale intensificando il collegamento tra il riflesso astrale dell'incantatore e lo spirito materiale. Questo collegamento viene intensificato utilizzando l'energia astrale dello spirito, "scollegando" il soggetto dal piano materiale. Questa tecnica richiede una grande concentrazione, ma permette di accedere ad un potere immenso. Questo potere però ha un costo. Ogni volta che il soggetto trasferisce il suo spirito per attingere al piano astrale, parte di esso rimane perso nel collegamento, finchè tutto lo spirito del soggetto, e quindi la sua volontà non finisce nel piano astrale, diventando così un guardiano.

== Magia Emotiva

La magia emotiva è una forma di magia tipicamente umana. Funziona grazie alla capacità innata di alcuni elementi molto emotivi, di amplificare il proprio spirito ed il collegamento con il riflesso astrale mediante le emozioni. Ad esempio, un soggetto può esaltarsi ed entrare in uno stato di eccitazione per la battaglia ed ira. Questo stato alterato consente di attingere all'energia astrale ed utilizzare la magia in modo offensivo in battaglia. Allo stesso modo, uno stato di pietà e compassione permette di proteggere e curare gli altri. Questi stati alterati, negli individui meno esperti, possono essere ottenuti attraverso l'uso di sostanze. L'uso di questa magia però fa sì che l'incantatore al momento del lancio di un incantesimo, sia quasi interamente controllato dalle proprie emozioni, ed abbia in se una quantità enorme di energia astrale; se dovesse perdere il controllo rischierebbe di impazzire, l'eccesso di energia astrale sovraccaricherebbe la sua mente, facendolo diventare un essere in grado di provare solo l'emozione che lo ha sopraffatto, questa creatura viene normalmente definita demone.

== Magia del Sangue

In alcuni esemplari di razze senzienti, a causa di mutazioni alla nascita, scorre, assieme al sangue energia astrale, fusa con quest'ultimo; Per attingere a questa forma di potere, il soggetto deve tagliarsi e far uscire il proprio sangue, o utilizzare il sangue altrui, ed incanalarlo per ottenere diversi effetti. Questo tipo di magia è puramente fisico: ovvero il soggetto può crearsi appendici come artigli, placche protettive, corna e così via, ed usarle per attaccare, oppure creare proiettili da lanciare. A differenza delle altre forme di magia, l'incantantore che la utilizza non presenta un rischio per la società, in quanto, dovesse abusarne, semplicemente morirebbe dissanguato. 