= Ambientazione sconosciuta
:toc: left
:toc-title: Indice
:icons: font

== Struttura del mondo

=== Creazione:

All'inizio i 2 piani erano uniti, l'energia e la materia erano uniti. Grandi concentrazioni di energia hanno iniziato a spostarsi, e ad "agire" da sole. Questo ha portato alla nascita degli elementi che hanno iniziato a separarsi, ed a manifestarsi sulla materia. Questa separazione ha portato ad uno scisma tra i due piani, separando il materiale dal piano dell'energia. Il mondo è stato creato da queste manifestazioni di energia, che col tempo hanno iniziato a sviluppare una "coscenza" anche se non si tratta di una vera e propria coscenza di se. Hanno poi iniziato a creare la vita, prima sottoforma di piante, poi animali, fino ad arrivare a creare i draghi, i quali sono stati creati come rappresentazioni degli elementi, seppur in forma molto più ridotta rispetto ai loro creatori. I semidei, vedendo la bellezza delle loro creazioni, hanno scelto di manifestarsi ad essi nella loro forma. Solo allora, da agglomerati di energia pura, e senza forma sono passati ad essere i grandi dragoni. I draghi vivevano liberi ed incontrastati ovunque nel mondo, ma riconoscevano nell'isola di Valentar la loro casa, dove risiedevano i 9 semidei. Col tempo poi altre forme di vita hanno iniziato a svilupparsi, con l'aiuto dei grandi dragoni, soprattutto Londrun. Ha reso possibile la nascita e lo sviluppo delle prime civiltà: gli elfi alti e gli umani. I primi, creati da Londrun, sono stati poi benedetti da Drogshul con una connessione al piano astrale particolarmente accentuata. Gli umani invece, inizialmente erano liberi, visti dagli elfi come poco più che animali selvaggi e violenti. Col passare dei secoli nuove razze hanno iniziato a spuntare, come i nani, benedetti da Jotraanviir con una conoscenza profonda della roccia e dei metalli, e gli gnomi, prediletti da Drogshul, dotati di una straordinaria intelligenza 

L'universo è diviso in 2 parti: 

* Piano Materiale
* Piano Astrale

I 2 piani sono separati ma allo stesso tempo collegati. Sono divisi da una "barriera", e collegati da portali. Inoltre il collegamento tra i piani varia in forza a seconda del luogo. In cima alla montagna ai confini del Regno di Balir ad esempio, risiede Avyumakra, il grande dragone bianco, signore dell'inverno, e la montagna stessa è infestata da elementali di ghiaccio. Nei pilastri invece, dopo la catastrofe che ha spazzato via la civiltà, la barriera che separa i due mondi è spezzata, e la sua rottura ha portato al riversamento di energia dal piano astrale in quello materiale, causando varie mutazioni ed epidemie; è dove buona parte dei mezzosangue vivono, assieme agli aviani.

=== Piano Materiale

Il piano dove vivono quasi tutti i mortali. Composto da 5 continenti principali: Valentar, Talenalia, Gorlanos, Ar-hadda, Vallea.

* Valentar
** Il continente dove per prima è comparsa la vita intelligente, sottoforma di draghi. Composto da un'unica isola ora è l'unico rifugio di molti draghi, nonché il loro principale cimitero, ed il centro del culto dei grandi dragoni.
* Vallea
** Vallea ospita perlopiù umani. La maggior parte del continente è territorio dell'Impero degli uomini, o di Adahimia. Il continente è diviso in 2 isole: Vallea, l'isola più grande, e l'isola volante di Arquel, che ospita l'omonima capitale imperiale.
* Talenalia
** Il continente, prende il nome da Talena, la matriarca e regina degli elfi alti. Il continente è attualmente diviso in 4 nazioni: Matriarcato di Talena, Regno di Balir, Terre Selvagge di Yas e la Legione di Tilgan. Il continente è composto da 4 isole, Talenalia, l'isola principale contesa tra barbari di Yas, il popolo di Balir ed il Matriarcato, Elelia, lo scudo del sud, occupato dalla Legione di Tilgan, Valelya, centro di studio religioso e magico del Matriarcato, e Marelia, terra perennemente spazzata da venti gelidi, dove si trova Yas.
* Ar-hadda
** Ar-hadda, comunemente noto come I Pilastri di Ar-hadda, o Pilastri, era un'unica isola, luogo d'origine della razza elfica. Dopo un'enorme catastrofe dovuta alla loro arroganza, l'isola è emersa dalle acque, e si è spaccata formando un arcipelago di fiordi e altopiani. Il continente ora è spazzato da costanti tempeste di pura energia magica, emanata da quella che era la capitale elfica, che ora prende il nome di Krater, ha mutato gli elfi, i loro schiavi umani e quasi tutte le creature che popolavano il continente, mutandole e generando gli abomini noti adesso come gli uomini-bestia e gli aviani.
* Gorlanos
** Gorlanos, oggi comunemente noto come Terre Libere del Nord Ovest è un piccolo continente, variegato, in cui 6 piccole fazioni si contendono la supremazia.

=== Piano Astrale

Il piano astrale è un grande vuoto, privo di luce, dove l'energia e quindi la magia, scorre in flutti come fosse un fiume, è il dominio di dèi, demoni e guardiani, che si muovono come esseri di pura energia. Gli unici elementi "solidi" che occupano il piano astrale sono i viaggiatori che utilizzano il piano per spostarsi lungo grandi distanze, i vari portali che collegano parti del mondo, e le "ancore" dimensionali utilizzate come punto di riferimento per il viaggio: si tratta di strutture che esistono sia nel materiale che nell'astrale. Agiscono un po come fari, contornati dal riflesso astrale di tutti gli esseri viventi che popolano il mondo. Vi sono inoltre delle piccole enclave di elfi astrali, ed una loro città.

== Razze senzienti

[cols="3", options="header"]
|===
^.^|Razza			^.^|Descrizione																	^.^|Magia			
^.^|Umani			^.^|Standard umani																^.^|D, E, S		x
^.^|Elfi Alti		^.^|Secondi creati al mondo, arroganti											^.^|D			x
^.^|Elfi Silvani	^.^|Elfi "buoni", guardiani della natura										^.^|D, E		x
^.^|Elfi Astrali	^.^|Elfi alti che hanno abbandonato il piano materiale e vivono nell'astrale	^.^|D			x
^.^|Driadi			^.^|Silvani che reincarnano lo spirito					  						^.^|E,			x
^.^|Goblin			^.^|Piccoli orcoidi intelligenti, affini alla magia								^.^|D, E		x	
^.^|Orchi			^.^|Orcoidi di taglia media, poco intelligenti									^.^|S			x
^.^|Ogre			^.^|Orcoidi grossi, quasi privi di intelligenza									^.^|X			x
^.^|Lucertoloidi	^.^|Draconidi bipedi, affini al sangue e al piano astrale						^.^|D, S		x
^.^|Coboldi			^.^|Piccoli draconidi bipedi che adorano i metalli preziosi 					^.^|E			x
^.^|Draghi			^.^|Quadrupedi alati simili a felini, affini agli elementi						^.^|D, E		x
^.^|Viverne			^.^|Draconidi alati bipedi, poco intelligenti									^.^|X			x
^.^|Nani			^.^|Standard nani																^.^|E			x
^.^|Gnomi			^.^|Piccoli umanoidi, molto intelligenti, grandi accademici						^.^|D, E		x	
^.^|Vampiri			^.^|Non morti che migliorano in capacità fisica col tempo						^.^|D, E, S		x	
^.^|Aviani			^.^|Elfi alati, vivono distaccati dal mondo										^.^|X			x
^.^|Mezzosangue		^.^|Uomini-bestie, mezz'orchi e mezzi draghi									^.^|D, E, S		x
^.^|Demoni			^.^|Manifestazioni meteriali delle emozioni, e maghi che perdono il controllo	^.^|D, E, S		x
^.^|Guardiani		^.^|Manifestazioni meteriali delle emozioni, e maghi che si distaccano dal mat	^.^|D, E, S		x
^.^|Divinità		^.^|Riflessi astrali delle credenze del piano materiale, e emozioni				^.^|D, E, S		x
^.^|Semidei			^.^|Creature del piano materiale con discendenza divina							^.^|D, E, S		x
|===	

* Umani: Razza che, con l'aiuto di Londrun si è distinta dai primati, formando società tribali e dimostrando grande capacità di adattamento. Col passare del tempo, dall'isola di Vihr sono migrati e si sono spostati in tutti i continenti, ma il principale gruppo di umani si è stabilito nell'isola di Vallea. Insediamenti umani si trovano principalmente in Vallea, dove è stato formato l'impero, a nord, nel continente di Gorlanos, e Talenalia.

* Elfi Alti: Creati da Londrun in un'era in cui i primi umani iniziavano a distinguersi dai primati, inizialmente erano creature immortali, ma dopo la catastrofe che li ha decimati, assieme alla distruzione del continente di Arhada sono stati puniti da Kaalvurn, che li ha privati della loro immortalità. Poco prima della catastrofe, un gruppo di elfi si è ribellato, e si è stabilito nelle varie foreste  del mondo, soprattutto nel continente di Gorlanos, deidcandosi alla protezine della natura, formando una razza separata, gli elfi silvani. Oggi gli elfi alti vivono in media 3 o 4 secoli, e sono dediti alla magia ed alle arti: non ci sono al mondo orefici, artisti o architetti migliori di loro. La loro cultura estremamente raffinata, unita alla loro iniziale immortalità, li ha resi arroganti e superbi, e la perdita della loro immortalità li ha resi più ostili verso le altre razze, soprattutto i mezzosangue e gli aviani, i quali ricordano loro della catastrofe che li ha portati alla loro condizione attuale. Esteticamente si presentano come creature alte quanto un umano, con lineamenti più snelli e longilinei, e movimenti più aggraziati; la caratteristica principale che li distingue dagli umani però sono gli occhi, che hanno tonalità che vanno dal giallo all'azzurro, passando per il blu, il viola, il rosso e l'arancione. Altra caratteristica distintiva delle razze elfiche sono le orecchie, che terminano a punta.

* Elfi Silvani: Inizialmente Elfi Alti che popolavano la città-tempio di Yle Thalor e le foreste sacre intorno ad essa, con il passare del tempo si sono lentamente trasformati in protettori della foresta stessa, e delle creature che vi abitavano. La foresta infatti era considerata come la culla della specie elfica, il luogo in cui Londrun ha creato i capostipiti della razza. Con il degenerare della società elfica, verso un uso sfrenato e sconsiderato della magia unita alla tecnologia, e l'idea che essendo stati creati "perfetti", il mondo fosse loro da sfruttare come preferivano, i fedeli di Londrun si sono ribellati, in un disperato tentativo di riportare all'ordine la società. Questa guerra però li vide spazzati via, la foresta venne abbattuta quasi del tutto, ed il grande tempio di Londrun a Yle Thalor saccheggiato e bruciato. In pochi riuscirono a fuggire, verso l'isola di Valentar, dove hanno fondato una nuova città: Londaure, situata sulla punta sud occidentale dell'isola. Lì conducono un'esistenza dedita alla protezione della foresta e degli esseri viventi che popolano l'isola e la proteggono anche dalle varie incursioni di orchi e mezzosangue che arrivano da Arhada. Hanno come fine ultimo però quello di tornare alle rovine di Yle Thalor, e ricostruire la città. Col tempo hanno stabilito diverse enclavi nelle foreste del mondo, e sono generalmente tollerati dalle altre specie senzienti. Hanno ottimi rapporti con i nani di Norlyn, soprattutto per l'astio comune nei confronti degli Elfi Alti e delle razze impure. Fisicamente somigliano molto agli altri elfi, tranne che per la carnagione più scura e la struttura corporea più simile ad un umano. La maledizione di Kaalvurn ha colpito anche loro, ma, grazie alla loro devozione, hanno la possibilità, alla morte, di reincarnare lo spirito in quelli che a tutti gli effetti sono elementali della natura: Driadi.

* Elfi Astrali: Potenti maghi elfici che hanno dedicato tutta la loro esistenza a tenere un equilibrio tra magia e vita materiale: invece di distaccarsi completamente dal proprio corpo, sono riusciti a trascendere l'esistenza dal piano materiale a quello astrale. Raggiungere ed essere ammessi a Caras Astra è l'aspirazione più grande di molti studenti delle varie accademie di magia sparse per il mondo, ma in molti falliscono, soprattutto membri delle altre razze. Buona parte della popolazione di Caras Astra infatti è composta da Elfi Alti, mentre le atre razze sono presenti, ma di rado superano la decina di membri. Gli Astrali, essendosi distaccati quasi completamente dal piano materiale, rinunciano a qualsiasi fedeltà verso le varie razze o nazioni, concentrandosi nella meditazione e nel cercare di unire il corpo e lo spirito. Un'altra funzione importante che svolgono è quella di aiutare i guardiani, cercando e distruggendo i demoni sia sul piano materiale che astrale.

* Driadi: Quando un Elfo Silvano percepisce che la sua vita è prossima alla fine, in genere oltre i 350 anni, può scegliere se accettarne la fine, o sottoporsi ad una prova: si dovrà recare al tempio di Londrun nella città di Londaure, ed offrirsi come eterno protettore della vita. Se la sua offerta viene accettata dal Gran Sacerdote, verrà tenuta una cerimonia funebre in suo onore, ed egli verrà scortato alle rovine del tempio di Yle Thalor, dove verrà abbandonato. L'aspirante protettore entrerà in meditazione nella foresta, cercando di comunicare con le varie creature che la popolano. Se riesce ad entrare in contatto con la vita della foresta, la foresta stessa lo accoglierà come parte di essa. Lo spirito dell'elfo si unirà al proprio riflesso astrale, mentre il corpo muta: la pelle diventa più scura e dura, simile in sembianze al legno; i tratti facciali si fanno più accentuati, scompaiono gli organi riproduttivi, ed i capelli. Gli occhi diventano bianchi, e la bocca si chiude. Il naso rimane, ed è attraverso quello che il driade respira. Perde il bisogno di mangiare, trae infatti nutrimento dal terreno. Gli arti superiori si allungano, fino a sfiorare il terreno, e le dita diventano delle punte accuminate. Con il tempo, una volta che il driade si è adattato al proprio corpo, può controllarne lo sviluppo: in alcuni casi infatti un driade può presentare delle corna, o 4 zampe, o 4 braccia, e così via; il cambiamento che avviene più spesso però è il ripristino dell'aspetto che l'elfo aveva in vita, tramite la crescita di fogliame dove una volta aveva i capelli. Una volta terminata la rinascita, il driade può scegliere dove servire, in genere ritorna al suo luogo natio. Il driade è in grado di comunicare telepaticamente con qualsiasi creatura senziente, ed a livello empatico con animali e piante. Ciò significa che percepisce le emozioni di tutte le creature intorno a lui, ed ha un buon controllo sugli animali. A volte questa connessione indesiderata può portare ad un sovraccarico emotivo, ad esempio durante una devastazione del luogo che sta proteggendo, e può causare la temporanea o permanente follia del driade.

* Orcoidi: Le specie orchesche rientrano tra le prime forme di vita create, e possedevano un'intelligenza molto basilare. Questi proto-orchi mostravano una grande capacità di adattamento all'ambiente, e notevole aggressività, che ha permesso loro di sopravvivere alle prime fasi del mondo. L'organismo degli orcoidi è un qualcosa di unico, in quanto sembra che le dimensioni siano correlate con l'intelligenza della creatura. Sono stati impiegati dagli elfi come schiavi, e dopo secoli di riproduzione selettiva di questi animali intelligenti, si sono distinte 3 tipologie di orcoidi.
** Goblin: Il goblin è il più piccolo, ed il più intelligente degli orcoidi. Alti circa quanto uno gnomo, hanno la pelle di un verde che varia a seconda dell'età della creatura, i lineamenti sono pronunciati, soprattutto il naso ed il mento. Sono gli unici membri della specie che possono praticare il distaccamento astrale. Molti elfi erano soliti tenere goblin come animali da compagnia, o come servi di studiosi e maghi. In rari casi hanno servito anche come assassini e spie. Dopo la catastrofe, molti di loro sono stati abbandonati a loro stessi, altri si sono ribellati contro i loro padroni, ed hanno iniziato a formare piccole società tribali. Come gli altri membri della specie si sono diffusi in tutto il mondo, dove infestano soprattutto il sottosuolo. La specie orchesca non ha subito grosse mutazioni dalla catastrofe, ma piuttosto ha ottenuto un'accentuazione delle caratteristiche che distinguevano le loro razze.
** Orchi: L'orco è una creatura relativamente stupida, che si aggira intorno ai due metri di altezza, dalla pelle verdastra, e dalla mandibola pronunciata. Buona parte del cranio dell'orco è formato dal volto, largo e schiacciato, mentre il cervello è poco sviluppato. L'orco non possiede un'intelligenza sviluppata come il goblin, ma comunque è in grado di fare ragionamenti, seppur semplici, e parlare. Il fisico di un orco però è molto potente. Ha una struttura muscolare molto sviluppata, soprattutto nella parte superiore. Questo li ha resi guardie del corpo abbastanza buone, nonostante comunque covassero un certo risentimento nei confronti dei loro padroni. Venivano inoltre utilizzati come manovali: erigevano case, mura ed infrastrutture. 
** Ogre: L'ogre è una versione più grossa, violenta e stupida di un orco. Arrivano fino a 3 metri di altezza, con una muscolatura possente che li ha resi ideali per lavori pesanti. La testa è piccola, e la spessa pelle di un verde scuro. Gli ogre non riescono a praticare la magia, e sono quasi del tutto immuni all'energia astrale. Sono in grado di parlare, nonostante il loro linguaggio sia articolato come quello di un bambino di 5 anni. Hanno avuto un impiego limitato nella società elfica, vista la loro stupidità, ed instabilità, ed oggi ce ne sono molto pochi. Come gli altri orcoidi, si sono insediati in ogni parte del mondo, costruendo rudimentali accampamenti dai quali lanciano raid agli insediamenti vicini.

* Lucertoloidi: I lucertoloidi sono stati creati dopo i coboldi, e rappresentano i primi tentativi di creare delle creature draconiche affine agli elementi. Come dimensioni sono paragonabili ad un umano. La testa è simile a quella di un serpente, gli arti anteriori, come nei coboldi, sono più lunghi, anche se più proporzionati rispetto ai loro cugini. Le mani ed i piedi terminano in dita artigliate, ed entrambe le estremità sono palmate. La pelle è squamosa, e come per i draghi, il colore varia a seconda dell'elemento a cui somigliano. A differenza dei draghi però, non hanno capacità di soffio o simili. Il colore della pelle ne determina le caratteristiche fisiche: i lucertoloidi azzurri sono in grado di muoversi più silenziosamente, e nascondersi meglio degli altri; quelli blu sono eccellenti nuotatori, e sono in grado di respirare sott'acqua; quelli bianchi resistono molto bene al freddo, e, anch'essi sono in grado di respirare sott'acqua. I lucertoloidi dorati sono gli unici capaci di utilizzare la magia; quelli marroni sono fisicamente più grossi, e molto più resistenti. I lucertoloidi rossi resistono al caldo molto bene, e sono ottimi combattenti. Quelli neri sono immuni a veleno e malattie, di cui hanno un'innata conoscenza. I lucertoloidi verdi sono in grado di rigenerarsi, ed hanno una conoscenza innata della natura tale da renderli ottimi guaritori; ed infine quelli viola sono molto più rapidi nei movimenti, e di gran lunga più astuti.

* Coboldi: I coboldi sono piccole creature draconiche intelligenti. Tendono ad essere più piccoli dei goblin, ed esili. La testa, simile a quella di un coccodrillo o alligatore, è dotata di una mandibola abbastanza potente per le dimensioni, e di denti piccoli ma affilati. I lunghi arti superiori terminano in 4 dita artigliate, e così anche i piedi. La pelle è squamosa, di colore biancastro sul ventre, mentre il dorso, gli arti e la testa hanno tonalità variabili, ma che in genere vanno dal verde al marrone-rossastro. Il coboldo possiede una rudimentale forma di intelligenza. Hanno un linguaggio complesso, e sono in grado di incanalare le proprie emozioni per lanciare magie. Col tempo il coboldo si è evoluto dall'essere una creatura che cammina su 4 zampe, ad una completamente bipede, in grado di creare ed utilizzare attrezzi rudimentali. Si trovano principalmente sull'isola di Valentar, ma anche nelle foreste dei continenti del nord. Sono attratti dai metalli e dalle pietre prezione, ed hanno una compulsione a rubarne il più possibile. Se minacciato un coboldo generalmente tenterà la fuga, a meno che non sia in un gruppo che ha il vantaggio numerico dalla sua parte.

* Draghi: I draghi sono stati creati come rappresentazione vivente degli elementi. Sono grossi quadrupedi alati, molto intelligenti, con un lungo collo ed una coda altrettanto lunga. A seconda del colore, si denota una particolare affinità ad un elemento, e delle caratteristiche fisiche variabili. La struttura di base però rimane sempre la stessa. Sono creature molto intelligenti, in grado di parlare. Solitamente sono neutrali nei confronti delle altre razze senzienti, e di rado attaccano deliberatamente. Alcune tipologie di drago instaurano persino dei rapporti con altre specie senzienti, soprattutto con gli Elfi Silvani, ma accade anche con gli umani. 
** Azzurro: Un drago azzurro è un drago nato per volare. Ha una pelle sottile, composta da piccolissime squame, indistinguibili tra loro a meno che non si esamini la pelle da vicino, le ossa cave ed un corpo snello; è il più piccolo tra i draghi, ma anche il più veloce ed agile. Si nutre principalmente di uccelli, ma non è raro vederlo nuotare nei vari mari del mondo a caccia di pesci. A differenza della maggior parte degli altri draghi, è privo di armi a soffio. Le sue armi principali sono l'agilità, i denti e gli artigli affilati, ed una placca ossea molto dura alla fine della lunga coda, che utilizza come una lama. La colorazione varia dall'azzurro cielo al blu chiaro, a seconda dell'età dell'animale.
** Bianco: Un drago bianco è generalmente più grande di un drago azzurro, anche se non di molto. A differenza dei draghi azzurri però, sono più tozzi e robusti, con delle protuberanze ossee che escono dalle scaglie biancastre che li ricoprono, partendo dalla nuca, fino alla coda. Il loro corpo è coperto da scaglie simili a scudi, e sono gelidi al tatto. Le ali, meno sviluppate rispetto agli altri draghi, consentono un volo lento e goffo rispetto agli altri esemplari, ma comunque più veloce di un cavallo al galoppo. I draghi bianchi vivono nei luoghi più freddi del pianeta, come cime delle montagne o le distese ghiacciate tra marelia e talenalia. Si nutrono di qualsiasi cosa riescano a trovare, e sono noti per aver attaccato insediamenti di umanoidi vari, anche se quest'opzione viene considerata solo in casi di estrema necessità. Un drago bianco può sopravvivere per mesi senza cibo, entrando in uno stato di ibernazione. Se minacciato, il drago attacca con un'arma unica alla loro specie: soffia una nube d'acqua simile ad una nebbia finissima, che però è a temperature molto basse. Questo fa si che appena entri in contatto con un qualsiasi oggetto formi uno strato di ghiaccio, che rende la vittima incapace di muoversi, sigillandola in un blocco di ghiaccio.
** Blu: Il drago blu è l'esemplare che più si allontana dalla famiglia dei draghi: le zampe, più lunghe rispetto agli altri draghi, terminano in 4 lunghe dita artigliate e palmate, che li rendono eccellenti nuotatori. Il corpo è più simile ad un serpente seppur siano evidenti spalle e bacino, e le dimensioni sono simili a quelle di un drago azzurro. Le ali sono meno sviluppate rispetto agli altri draghi: il drago blu infatti non riesce a volare per periodi di tempo prolungati. La testa a forma di diamante nasconde due file di denti corti ma affilati, chiusi da una mascella capace di tranciare di netto un soldato in armatura con relativo cavallo, ed una cresta che percorre il drago per tutta la lunghezza. La colorazione varia dal celeste al blu notte, arrivando ad essere indistinguibile come colore da un drago nero negli esemplari più vecchi. Ci sono poche creature che attaccano deliberatamente un drago blu. Se attaccato sulla terra ferma o dalla superfice del mare, il drago usa la coda per atterrare o capovolgere in nemico, per poi balzargli addosso e dilaniarlo con artigli e denti, se invece il pericolo viene da sott'acqua, il drago prima affonda gli artigli anteriori sulla vittima, poi a seconda delle dimensioni di quest'ultima rispetto al drago, o l'avvolge e la stritola, o ne strappa le carni con gli artigli posteriori. Può anche capitare che una volta immobilizzata la vittima il drago prenda il volo e la faccia precipitare verso il suolo.
** Dorato (Oro): Il drago dorato è un drago imponente, dal collo lungo e gli occhi viola. È il drago con più capacità magiche, e di gran lunga il più raro. La loro pelle  è squamosa, ed alla nascita di colore bianco-giallastro. Con il tempo le squame iniziano ad ispessirsi ed acquistano un colore più acceso. Crescendo inoltre, le squame si coprono di una patina vitrea, che conferisce loro particolare lucentezza. La testa di un drago dorato è simile a quella del drago blu, ma un po più oblunga, e termina in una protuberanza ossea simile ad un becco. Due corna si distaccano dalla testa e formano una "S". In rari casi le corna possono a loro volta biforcarsi, ma succede solo agli esemplari più vecchi, ormai prossimi alla morte. Queste corna non hanno utilità difensiva, e sono presenti solo nei maschi. È estremamente raro che un drago dorato combatta, e se lo fa cercherà di portarsi a distanza per usare le sue capacità magiche. Se qualcosa però gli impedisce di allontanarsi, allora carica sfruttando la sua mole ed il becco come armi principali.
** Marrone: Un drago marrone è un drago di dimensioni ancora più grandi di un drago dorato. È coperto da una dura pelle coriacea sul ventre, di colore biancastro, mentre il resto del corpo è coperto di dure placche ossee, di un colore che va dal marrone-rossastro al marrone più scuro. Nonostante la mole imponente è sorprendentemente veloce, e le possenti ali gli permettono un volo prolungato, seppur goffo ed impacciato; terminano inoltre in due lunghe protuberanze ossee simili ad artigli. Le grosse zampe terminano in 4 dita artigliate. Sono creature pacifiche, che si muovono di rado, ed attaccano senza provocazione ancora meno. Non è raro infatti osservare piccole tracce di vegetazione crescere sugli arti e sul dorso del drago. Si nutrono di qualsiasi cosa riescano a trovare, e riescono a digerire persino metalli e rocce, e sono formidabili predatori se necessario. Se minacciati attaccano cercando di schiacciare l'avversario con il loro stesso peso. Nel caso sia un avversario della loro stessa taglia, usano sia le ali che le zampe per attaccarsi all'avversario e dilaniarlo con gli artigli e le zanne. Nonostante sia possibile avvistarne ovunque nella terra ferma, soprattutto nell'isola di Valentar, è più comune trovarli ai piedi delle montagne.
** Nero: I draghi neri sono visti come portatori di morte e malattie da parte delle altre razze senzienti, ed in parte è vero. Il drago nero è di dimensioni simili ad un drago dorato, con delle scaglie taglienti che vanno dal grigio scuro al nero. La testa del drago nero è coperta di piccole corna affilate che culminano in due lunghe corna che piegano leggermente in avanti. I lunghi denti del drago spuntano dalla mandibola. Le ali culminano, come nel drago marrone, in due lunghi artigli. Dal collo partono poi delle placche ossee appuntite. In combattimento il drago può fare ricorso a due armi molto pericolose, oltre ai denti e gli artigli che ha sulle ali: sotto la sua lingua infatti vi sono due ghiandole che secernono veleno. Il veleno che sputa in questo modo, generalmente viene direzionato verso gli occhi della vittima, accecandola, permettendo così al drago di colpire con più sicurezza. Se ingerito o inalato il veleno porta ad una morte dolorosa che sopraggiunge moltop rapidamente, a seconda della creatura colpita. Alternativamente, il drago può soffiare fuori il veleno, coprendo un'area più vasta. La nube porta i risultati del veleno sputato, ma con un effetto ridotto, a causa della minore concentrazione di veleno nella vittima. Un umano, paradossalmente ha più opportunità di sopravvivere ad un getto di veleno diretto rispetto ad un soffio però, in quanto l'area coperta dal soffio è molto grande. Come se non bastasse, il sangue del drago è velenoso, così come la carne. La stessa tossina che produce per lo sputo, viene trasportata dal sangue.
** Rosso: I draghi rossi sono i draghi che più sono diventati parte dell'immaginario popolare e del folklore tra le varie razze senzienti. Questo perchè tra le varie specie draconiche sono i più aggressivi. Il drago rosso è simile in dimensioni ad un drago bianco, ma è più snello ed alto rispetto ad esso. Le robuste ali terminano in due piccoli artigli, che gli consentono di arrampicarsi con facilità. La pelle è spessa, e lungo la parte anteriore del collo, ed il ventre, è coperta da scaglie biancastre molto dure, mentre delle squame rosse coprono il resto del corpo. Due file di piccole scaglie ossee partono dal naso dell'animale e lo percorrono in tutta la lunghezza, unendosi in una fila all'attaccatura della coda. I draghi rossi vivono ovunque sulla terra ferma, soprattutto in luoghi ricchi di grotte e caverne. Quando attacca, o viene attaccato, il drago utilizza come arma principale il suo soffio: l'animale produce, in un organo apposito, un liquido viscoso che si infiamma a contatto con l'aria. Quando soffia, la sua trachea si riempie di questo liquido, e si mescola con l'aria espulsa dai polmoni. Questo fa si che il liquido inizi a bruciare già all'interno del drago, e ha portato alla concezione errata che il drago soffi fuoco. In realtà, quando lascia la bocca del drago, il liquido che sta bruciando si attacca alla vittima e continua a bruciare, incendiando la preda. Un soffio prolungato è in grado di fondere il ferro, anche se di rado il drago concentra il suo soffio in un'area ristretta. Oltre alla preda, il drago mira ad incendiare l'area circostante, in modo da disorientarla ed impedirne la fuga, se non attraverso altre fiamme, o verso il drago stesso.
** Verde Il drago verde, nonostante il suo aspetto, è una creatura pacifica, e mansueta. Non è raro vedere draghi verdi fungere da cavalcature, o animali da compagnia, molto intelligenti ed in grado di parlare, ma pur sempre animali. Il drago verde ha un collo ed una coda più lunghi rispetto ad un drago rosso, ma le dimensioni sono molto simili. Dalla testa del drago partono due paia di corna, che curvano verso l'alto e in avanti. Le ali del drago verde sono molto sviluppate, e nonostante le dimensioni, può avvicinarsi molto come abilità al drago azzurro. Di rado attaccano di loro iniziativa, solitamente lo fanno solo per nutrirsi, o se sono impiegati come cavalcatura in battaglia, nonostante siano dei nemici temibili e molto potenti. Il drago verde si difende in un modo simile a quello del drago nero: produce infatti una bile molto acida, che è in grado di sputare in un getto prolungato. Questa bile è in grado di sciogliere completamente un'armatura nel giro di pochi minuti, e se l'acido entra in contatto con la pelle o pelliccia, in genere causa forti bruciature da acido, e non è raro che scavi un buco nella vittima. Alternativamente la bile può essere nebulizzata, questo copre un'area molto vasta di una nebbia irritante che può causare danni che variano dalla cecità temporanea alle ustioni o morte per soffocamento. Il suo soffio però non è l'unica arma di cui dispone. Non è raro vedere un drago verde utilizzare le corna per infilzare i nemici se messo alle strette, o ricorrere al morso ed agli artigli. Vista la loro connessione con Londrun, i draghi verdi sono ritenuti sacri dagli Elfi Silvani.
** Viola: Il drago viola è indistinguibile da un drago azzurro, tranne che per il colore. Anch'esso ha le ossa cave, le ali molto sviluppate ed una placca alla fine della coda. Vengono considerati da chi va per mari, come un di cattivo auspicio, in quanto la loro presenza indica una tempesta nelle vicinanze. I draghi viola amano particolarmente le tempeste, in quanto sono spesso accompagnate da fenomeni elettrici. Il drago è in grado di immagazzinare una carica elettrica nel suo corpo, o di generarla. Lungo il dorso, dopo l'attaccatura delle ali, fino alla coda, sono presenti degli organi appositi, che permettono al drago di scaricare l'elettricità generata a volontà. Generalmente viene scaricata attraverso la placca posta sulla coda del drago, che viene impiegata come una lama. La scarica elettrica che rilascia è abbastanza potente da uccidere qualsiasi creatura più piccola, o di stordire un altro drago. Solitamente innocui nei confronti delle altre specie senzienti, tendono a vivere lungo le coste, e non è raro vederli assieme ai draghi azzurri.

* Viverne: Le viverne sono animali intelligenti in grado di parlare, di razza draconica, nate da una perversione dei draghi da parte del dio elfico NOMEDIO. La viverna ha due ali terminanti in un lungo artiglio, che vanno a sostituire le zampe anteriori, mentre le grosse zampe posteriori sorreggono tutto il corpo della creatura. La testa è simile a quella di un drago, tranne che per un becco aquilino che va a sostituire la bocca. La pelle è composta di scaglie taglienti, che vanno dal marrone scuro al grigio. Dalla testa, lungo tutta la lunghezza del corpo si sviluppano piccole creste ossee, e la coda termina in un lungo pungiglione velenoso. La viverna non è grande come gli altri draghi, gli esemplari più vecchi infatti, rimangono comunque di dimensioni inferiori ad un drago azzurro o viola. Sono feroci predatori che vivono in piccoli branchi di 5 o 6 esemplari. Attaccano qualsiasi creatura deliberatamente, e, se in branco, rappresentano un serio pericolo anche per un drago dorato o marrone. Sono in grado di comunicare tra loro, ed in genere con altre specie draconiche, ma la comunicazione è in genere molto superficiale.

* Nani: Jotraanviir, vedendo la creazione degli elfi, plasmò dalla roccia delle creature umanoidi, più basse e robuste, che più rispecchiavano la roccia da cui erano stati creati. In seguito chiese a Londrun di dare vita alle creature, il quale, divertito dall'aspetto dei primi nani, acconsentì. I primi nani nacquero così dalla roccia, e vennero subito benedetti dal signore delle montagne con una grande conoscenza dei metalli e delle pietre preziose. I nani vivono a lungo, circa 2-3 secoli. Inizialmente vivevano a Gorlanos, nella città che oggi si chiama Norlyn, ma col tempo si sono spostati prima su tutta la zona nei pressi della montagna stessa, e poi sentendo voci di grandi ricchezze ad est, alcuni gruppi si sono stabiliti a Talenalia, e Vallea. Nei confronti delle altre razze sono generalmente diffidenti. Dopo la catastrofe e la migrazione elfica, sono entrati in contatto con gli elfi: dopo qualche scaramuccia, ed un lungo processo diplomatico, i nani della montagna hanno accolto gli elfi silvani, consentendo loro di popolare la grande foresta ad ovest della montagna. Più o meno lo stesso è stato per i nani di Balir, seppur più rapidamente: gli elfi silvani vivono nella foresta a nord di Exeter, la vecchia capitale nanica. Nei confronti degli elfi alti invece c'è un rapporto di disprezzo reciproco, che ha portato ad una lunga e devastante guerra.

* Gnomi: gli gnomi sono una razza comparsa dopo la catastrofe di Krater. Sono piccole creature bipedi, che raramente superano il metro di altezza, con tratti somatici che ricordano molto gli elfi. Sebbene le loro origini siano incerte, non è da escludere che siano anch'essi una mutazione della razza elfica, dovuta alle tempeste astrali. Gli gnomi presentano una forte sintonia con il piano astrale, ed un'eccezionale intelligenza. Vivono come gli umani, circa un secolo, e non hanno formato una nazione indipendente, bensì si sono mescolati alle altre razze, inserendosi nelle società come accademici, studiosi e sapienti. Vista la loro astuzia, non è raro che vengano impiegati come consiglieri e diplomatici, soprattutto nelle nazioni umane. Un piccolo gruppo di gnomi, stabilitosi a Norlyn, si è adattato molto in fretta alla vita sottoterra, ed hanno appreso dai nani il loro amore per le pietre preziose.

* Elfi Aviani: Dopo la catastrofe che ha devastato Arhada, gli elfi sono fuggiti dal continente, migrando verso nord e nord-ovest. Non tutti però sono riusciti a fuggire, ed alcuni di loro sono stati mutati dalle tempeste astrali che spazzano l'isola. Gli elfi aviani sono una mutazione intelligente degli elfi, che attraverso secoli di evoluzione accelerata, sono diventati un ramo semi-stabile della specie elfica. Le varie mutazioni degli esseri senzienti del continente hanno portato a molti esemplari di creature mutate, ma gli aviani si sono distinti in quanto sono una delle poche mutazioni non sterili. La loro capacità di volare inoltre, ha ridotto l'esposizione alle prime e più devastanti tempeste: all'occorrenza infatti, semplicemente se ne andavano. Col tempo, e vista la longevità degli elfi, da elementi singoli si sono uniti in piccoli gruppi, che si sono insediati nelle città più esterne del continente, soprattutto a sud. Fisicamente gli aviani si dividono in 4 caste, a seconda del grado di mutazione: nome1, quelli che mantengono di più l'aspetto elfico: le ali prendono il posto delle braccia, e terminano in 3 artigli che usano come mani. I nome1 sono la casta governante, e di sacerdoti. Nome2 indica gli aviani con un grado di mutazione superiore, ma che mantengono comunque visibili tratti elfici, e l'intelligenza che avevano un tempo; anche loro hanno le ali al posto delle braccia, ma oltre a quelle, la parte inferiore delle loro gambe è simile a quella di un uccello. Un collare di piume ne adorna il collo e copre le spalle. Nella società ricoprono ruoli di istruzione e supervisione, sono quelli più dotati nell'uso della magia. La terza casta, nome3 indica gli aviani il cui corpo è completamente ricoperto di piume, conservano ancora le braccia che avevano un tempo, anche se sono alate. La parte inferiore del corpo è quella di un uccello, con le zampe che terminano in 3 artigli, ed il ginocchio invertito. Sono mediamente intelligenti, e nella società sono artigiani rispettati. Nome4 indica invece tutti gli aviani che non sono in grado di volare. Buona parte di essi è completamente ricoperta di piume, ma privi di ali. Le braccia terminano in mani artigliate, la testa è più piccola, e le gambe sono quelle di un uccello. Nella società aviana fungono da costruttori, agricoltori, servi, e fanteria.

* Vampiri: Sebbene non siano propriamente una razza a se stante, i vampiri sono più diffusi di alcune razze, ed hanno una loro nazione, la Repubblica Scarlatta. Il vampirismo si è presentato come una malattia incurabile, che, nel corso di poche settimane, settimana, causa la perdita di forze e vitalità nella vittima, fino a causarne la morte. In certi casi però, se la vittima è abbastanza forte, la malattia la fa entrare le vittime in uno stato di coma profondo simile alla morte, che può variare in durata dalle poche ore ai giorni. Se la vittima si risveglia, sente l'impulso di nutrirsi di carne, ma soprattutto di sangue. Qualora ci riesca, il corpo lentamente si ricostituisce, tornando a com'era alla contrazione della malattia. Inoltre, col tempo, il vampiro nutrendosi rinvigorisce, e le sue capacità fisiche migliorano notevolmente. La morte però sembra non sopraggiungere mai: i vampiri infatti sono immortali, anche se possono essere uccisi. Fisicamente un vampiro appena risvegliatosi dal coma, si presenta come un umanoide dal pallore mortale; è freddo al tatto, non respira ed il cuore non batte. Il corpo si presenta come quello che aveva in precedenza, tranne per il fatto che la massa muscolare è scomparsa quasi del tutto, i capelli sono diventati completamente bianchi e la pelle si è ritirata. Nutrendosi, i muscoli tornano a svilupparsi, e riacquista l'aspetto di un essere vivente normale, tranne per il pallore che rimane, così come la temperatura corporea bassa. Le unghie si fanno accuminate, somigliando quasi ad artigli, e lo stesso accade ai denti. Se possibile i vampiri vengono distrutti al più presto, in quanto un vampiro lasciato a se stesso è una minaccia per la società. Sono pochi i luoghi dove un vampiro è accolto con rispetto, in molti casi infatti, appena rende nota la sua natura, si vede contro interi regni. L'unica eccezione è la Repubblica Scarlatta, che attraverso un rigido codice sociale, e un ottimo corpo di diplomatici, intrattiene rapporti commerciali e di aiuto militare con alcuni regni confinanti.

* Mezzosangue: I mezzosangue si dividono in due tipologie principali: gli uomini-bestia, e gli incroci. I primi sono generalmente disprezzati ed odiati, mentre i secondi sono almeno tollerati, anche se in alcune culture sono emarginati.
** Uomini-bestie: Per uomo-besta si intende una mutazione semi-stabile di un essere vivente. Viene adottato il termine uomo in quanto le mutazioni delle altre razze senzienti sono meno frequenti, o generalmente più instabili e meno longeve. Un uomo bestia quindi piò essere un qualsiasi essere bipede senziente, che ha subito una mutazione, ottenendo delle parti del corpo, e/o comportamenti animali. La mutazione può avvenire a causa di effetti magici, o essere trasmessa da un genitore già mutato, e può essere temporanea, o permanente. Nel caso la mutazione sia congenita, ovvero presente dalla nascita, generalmente il piccolo viene ucciso. Se appare durante lo sviluppo, o a causa di effetti magici, il soggetto viene risparmiato, ma condurrà in genere una vita ai margini della società. In molti casi gli uomini bestia abbandonano la civiltà, e si riuniscono in piccole tribù, che possono avere anche comportamenti violenti nei confronti delle razze "pure". Non è raro che diventino razziatori e saccheggiatori. In genere le tribù mantengono numeri ridotti, in quanto la sabilità fisica e mentale dei singoli membri rende un'organizzazione complessa abbastanza improbabile.
** Incroci: un incrocio è un  figlio nato da un rapporto tra due razze senzienti. Ad eccezione dei mezzi draghi, che sono largamente accettati e stimati nella società, gli altri incroci sono tollerati, ma può capitare che vengano leggermente marginalizzati o discrimminati. Gli incroci con la specie orchesca in particolare vengono discriminati da gran parte della società.

* Demoni: Maghi più o meno potenti, che non sono stati in grado di controllare il loro potere, il quale li ha consumati. Succede solo a maghi che utilizzano le proprie emozioni, o il potere del sangue per invocare la magia. Una volta consumati, cercano fonti di nutrimento attraverso le quali accrescere il loro potere. Diventano esseri di magia pura, che hanno come obiettivo consumare creature simili a loro, sia sul piano materiale che astrale. Sono in grado di spostarsi liberamente tra i due. I più deboli in genere iniziano ad accrescere il loro potere nutrendosi delle emozioni degli esseri viventi, e cercando di assorbirne lo spirito. I più potenti invece spesso attaccano Caras Astra, o qualsiasi guardiano trovino. Seppur privi di intelligenza, hanno un istindo di sporavvivenza e coscenza di se.

* Guardiani: Maghi più o meno potenti che si distaccano troppo dal piano materiale, volontariamente o meno, diventando dei gusci nei quali l'energia astrale, quindi la magia, scorre quasi liberamente. Il loro corpo viene animato da questa energia, e trattengono una minima parte della loro intelligenza. I guardiani si trovano spesso dove ci sono grandi concentrazioni di energia astrale, poiché ne sono attratti; sono molto sensibili alla magia, e la loro natura semi senziente li rende ottime guardie del corpo di maghi e viaggiatori astrali. A differenza di un demone, consumato dalle proprie emozioni, il distaccato guardiano cerca di controllare l'energia astrale che lo pervade, e di portare un equilibrio tra se stesso e ciò che lo circonda. Vede i demoni ed alcuni utilizzatori di magia come creature deplorevoli, e cercherà di distruggerle sempre, per restituire l'energia astrale che hanno rubato. 

== Sul tempo

Il tempo nel mondo scorre in modo particolare. Il pianeta ha un'orbita ellittica scentrata intorno ad un sistema binario, il che lo porta a compiere un giro completo in 4 anni. ogni ciclo di 4 anni

== Sulle fazioni

=== La nobiltà nel mondo:

Le varie fazioni del mondo hanno sviluppato una loro cultura, e dei sistemi di nobiltà diversi.

==== Gorlanos

La nobiltà nel continente di Gorlanos è la classe dominante, ed i titoli sono ereditari. Nella Repubblica Scarlatta e nella Gilda della Fenice i titoli nobiliari con il passare dei secoli sono caduti in disuso, mentre negli altri regni del continente è ancora la classe dominante, anche se i nomi hanno subito variazioni.

Impero di Meridia:: 
Imperatore
Duca
Barone
Principe
Cavaliere

Regno Del Sottosuolo::
Re della Montagna
Principe
Reggente
Mastro

Ducato Vulic::
Gran Duca
Conte
Barone
Signore

Principato di Carenia::
Principe Reggente
Conte
Signore

==== Shorlea

Nel continente di Shorlea la nobiltà svolge ancora un ruolo primario nel governare la società, ad eccezione dei popoli barbarici noti come Ignariti, per i quali il grado di nobiltà è insignificante.

Figlie di Talena::
Madre suprema
Matriarca
Padrona

Regno di Balir::
Re della Montagna
Gran Principe
Governatore
Sovrintendente

Legione di Tilgan::
Comandante Supremo / Gran Ammiraglio
Generale / Ammiraglio
Governatore
Capitano del Popolo

==== Vallea

In Vallea,come nel continente di Shorlea, la nobiltà è al centro della vita politica

=== Arhada

Quelli noti ora come "I Pilastri", o "Pilastri di Ar-hadda", un tempo erano un unico continente che ospitava i le prime razze umanoidi. 

I Pilastri un tempo erano un unico altopiano in mezzo al mare popolato da un gruppo di avoral. Giunti sul piano subito dopo Adahim, lo hanno assistito nella creazione																	
e consolidamento del suo Impero. Circa 30 anni dopo il loro arrivo però, insoddisfatti della loro condizione e inorriditi dalla creazione dei draghi, gli avoral decisero																	
di abbandonare l'Impero; si spinsero quindi ad ovest, fondando la citta di Arhada al centro dell'altopiano. Qui vissero e prosperarono in pace per molti anni, finchè																	
ormai vicino alla sua morte, Adahim decise di vendicarsi e punirli per il loro tradimento di due secoli prima: Arhada venne completamente spazzata via, e, da 																	
isola, l'altopiano divenne un arcipelago. Ciò però non scoraggiò la popolazione locale, che ricostruì la sua capitale sul cratere di quella vuota, chiamandola appunto Krater																	
Inoltre, ogni isola del Pilastri venne collegata da enormi ponti di pietra, ed il popolo prosperò ancora di più. La famiglia imperiale però non tollerò questo affronto, e																	
 circa 250 anni dopo la morte di Adahim, l'Imperatore decise di vendicarsi: alla sua morte l'intera popolazione dei Pilastri sarebbe stata confinata in un unico libro,																	
costretti a rivivere i loro ultimi attimi di libertà, e la distruzione di Arhada all'infinito. Ora i Pilastri sono popolati da mostri e bestie di ogni sorta, e le le città sono 																	
deserte ed in rovina.																	

=== Gorlanos

==== Città Stato di Tedara

La città stato di Tedara era, ai tempi dell'Impero, il principale centro di addestramento e alloggio delle truppe imperiali. Dopo la fondazione di Staria ed il completamento della Torre delle Catene, l'imponente torre-prigione a nord ovest dell'isola, la sua importanza è notevolmente aumentata. L'effettiva separazione della città ed i																							
territori ad essa legati, risalgono a circa 350 anni addietro, quando, alla morte dell'Imperatore di Laria, vi erano 3 pretendenti al trono: il primo duca Vulic, il barone Vorth, e l'erede dell'Imperatore. La supremazia di quest'ultimo sugli altri fu dovuta ad una promessa di terre fatta al primo duca e a Vorth. che ricevettero																							
rispettivamente la città di Ederla e Staria. In seguito, Vorth, grazie alla sua magia, riuscì a contattare un'entità degli inferi che gli concesse l'immortalità. Grazie a questo dono, ed il suo controllo su demoni e diavoli, oganizzò un'evasione di massa dalla Torre delle catene, grazie alla quale riuscì a prendere il controllo su																							
Tedara, proclamandosi dittatore. Inizialmente la popolazione sottostava alla dittatura, più per paura che per volontà propria. Ribelli e dissidenti infatti, venivano deportati alla Torre, dove si dice venissero torturati. Col tempo però il Dittatore stesso, capì la pericolosità di ciò, e da circa due secoli ha avviato una modernizzazione																							
ed una guida "illuminata" del suo regno, pur intrattenendo molti rapporti con gli esterni malvagi su cui aveva fatto affidamento per reclamare il trono. Ora il popolo lo vede come un potente guardiano e protettore della loro libertà, e grande innovatore, accettando di buon grado il suo comando, nonostante non tutti siano 																							
favorevoli alla presenza degli esterni nelle loro città, pur considerandoli un male necessario alla difesa delle loro case. La città stato è tuttora in guerra con l'Impero di Meridia, mentre si mantiene abbastanza neutrale con gli altri regni.

==== Ducato Vulic

Il Ducato Vulic è nato in seguito ad una disputa sulla successione al trono Imperiale circa 350 anni fa, conclusasi con la promessa di terre ai due contendenti da parte del legittimo erede al trono. Inizialmente il Ducato comprendeva solo la città di Ederla e qualche villaggio ad essa legato. Successivamente, durante le 																							
epidemie che devastarono Meridia, la città divenne un importante scalo per il trasporto dei malati verso l'isola di Vagra. In seguito alle epidemie, il DUcato ha esteso la sua influenza alle città di Azug ed Icta, che sono passate sotto il diretto controllo di Ederla. Qualche anno dopo la secessione di Norlyn e delle isole del Mar d'Oro,																							
Il DUcato approffitto ulteriormente della debolezza dell'Impero per appropriarsi della città di Sindan. L'Impero, vista la rapida espansione del Ducato, e conscio della sua debolezza, stipulò un accordo di non belligeranza. L'ultimo duca mortale, è spirato circa 80 prima degli avvenimenti attuali, ed il trono è passato alla 																							

==== Gilda della Fenice

==== Impero di Meridia

Teria, Kheria, Carenia, Thudora, Wrokia e Turraia

L'isola di Meridia, la più grande del continente di Gorlanos, era tutta sotto il controllo dell'Impero locale, chiamato appunto Impero di Meridia. Le origini dell'impero sono da tracciare a 5 secoli prima della catastrofe; i primi insediamenti umani si sono espansi, fino a formare dei piccoli regni in contrasto tra loro. Per circa 350 anni questi staterelli si sono combattuti, e nel 1709CD, in quello che poi è diventato nel calendario imperiale l'anno 0 di Meridia, o Anno Meridiano, il regno di Teria, con capitale a Laria ha stretto un'alleanza con i regni orientali di Kantes e Ghellia e Kheria, formando un proto-impero, di cui si è nominata sovrana. Durante il suo regno, l'Imperatrice di Meridia si è impegnata ad unificare sotto la sua bandiera tutti i piccoli regni in cui era suddivisa l'isola, compito che però ha portato a termine il secondo imperatore di Meridia, suo figlio, nel 44AM (1753CD) L'impero in seguito alla sua unificazione è stato suddiviso in 7 province: Teria, con capitale Laria, Wrokia, con capitale Norlyn, Ghellia con capitale Lindos, Kantes con capitale Carelian, Kheria con capitale Medor, Turraia con capitale Ederla e Thudora con capitale Tedara. Le 6 province riconoscevano l'autorità del sovrano di Teria come Imperatore, ed erano legate da un accordo di sostegno comune, sia militare che commerciale, anche se non avevano molti rivali attorno. Inizialmente l'impero era molto stabile, ed ha prosperato, con la fondazione di accademie navali e militari, che promuovevano l'avanzamento tecnologico. Nel 72AM(1781CD), una disputa sulla successione vede le due province di Ghellia e Kheria scontrarsi. Alla guerra si aggiunge Turraia, schierata dalla parte di Ghellia. La guerra dura diversi anni, e nel 73AM(1782CD) intervengono anche le forze imperiali a cercare di ristabilire l'ordine. Temendo di perdere territori, Il duca di Ederla e governatore di Turraia ritira il proprio esercito, mentre la città di Lindos viene assediata. Nel 76AM(1785CD) la città si arrende, ed il governatore di Ghellia, come punizione per l'aggressione ad una provincia imperiale viene destituito. Parte dei territori di Ghellia vengnono annessi alla provincia di Kheria, che controlla tutte le isole orientali del continente. Il territorio compreso tra Kentos ed il mare viene assegnato al duca di Carelian, e la provincia viene rinominata in Carenia. Durante il periodo della guerra, alcune navi, provenienti principalmente da Turraia approdano sull'isola di Vagra, dove sono stati stabiliti piccoli insediamenti, quasi esclusivamente sulla costa. Per i 20 anni successivi gli insediamenti sono cresciuti, ed esploratori si sono portati fino al confine opposto dell'isola. Nel 93AM(1802CD) le colonie sull'isoa di Vagra, da territori della provincia di Turraia, sono diventati una provincia imperiale indipendente, che ha preso il nome dall'isola, e con capitale Sernost, ed il governatore della città venne nominato Barone.

==== Principato di Carenia

Le terre dei ribelli di Meridia, si estendono da costa a costa nel lato orientale dell'isola. La ribellione è l'epilogo di un malcontento serbato nei secoli verso l'imperatore. Lesilio dei malati durante le epidemie e la secessione dei vari regni dall'impero, non hanno fatto che aumentare questo malcontento, ed a dare l'idea che la tirannia																							
di Laria stesse per finire. Circa un secolo prima degli avvenimenti attuali, il comandante delle truppe a Carelian ha dato il via alla ribellione, uccidendo il governatore della città, e vari funzionari imperiali. Da allora, sfruttando i fiumi e la Barriera Verde, i comandanti della città mantengono il controllo su un'area relativamente vasta																							
dell'isola. Attualmente è controllata da un comandante militare, che funge anche da governatore, eletto dal popolo ogni 5 anni.																							

==== Regno Libero del Sottosuolo

Il Regno Libero del Sottosuolo era originariamente parte dell'Impero di Meridia, separatosi durante le epidemie che devastarono l'isola. Nella città di Norlyn, scavata sotto la montagna più alta dell'isola di Meridia, il regno ha iniziato a prosperare, soprattutto grazie all'ingegno ed industriosità della sua gente. La ricchezza di questo popolo, infatti è derivata dalla vendita dei loro prodotti ad alta tecnologia, come navi a vapore e costrutti. Gli stessi costrutti e navi, costituiscono gran parte della loro potenza bellica. Col passare del tempo, da una nazione di quasi esclusivamente gnomi e nani, il regno è diventato un miscuglio eterogeneo di tutte le razze del sottosuolo, e qualche umano occasionale. Il regno è sempre stato governato da un Concilio dei rappresentanti delle varie razze. Attualmente vi sono 3 rappresentanti per le razze principali (drow, nani, gnomi) e un rappresentante per le varie minoranze	(principalmente umani)	

==== Repubblica Scarlatta

L'isola di Vagra, essendo la parte più a sud del continente, è stata la prima ad essere colonizzata dai popoli provenienti da Arhada. All'epoca della catstrofe, la popolazione era costituita principalmente da elfi silvani ed i loro schiavi umani, insediatisi soprattutto nella parte settentrionale dell'isola, a causa delle frequenti incursioni di orchi e aviani, provenienti da Arhada e Valentar, e faceva parte dell'Impero di Meridia. Alla comparsa dell'epidemia di vampirismo, iniziata proprio sull'isola, probabilmente a causa di uomnini besta provenienti da sud, quasi tutta la popolazione è stata decimata. L'intera isola è stata messa in quarantena inizialmente, e con il passare delle settimane, e col diffondersi della malattia anche nelle coste meridionali di Meridia, tutti i collegamenti con l'isola sono stati completamente tagliati. Dopo alcune settimane, un gruppo di esponenti della nobiltà imperiale, sopravvissuti e trasformatisi in vampiri, hanno cercato di ristabilire l'ordine nell'isola, radunando le poche centinaia di persone immuni o mutate, ed hanno iniziato a ricostruire la città di Sernost, sulla costa nord-occidentale dell'isola, e di ristabilire i contatti con l'Impero. La delegazione inviata a Laria però, non ha fatto ritorno; al suo posto è arrivata una flotta imperiale che ha iniziato a bombardare la città, e a far sbarcare un esercito che l'ha occupata. La popolazione, ed il consiglio di nobili che governavano la città è fuggita ad est, rifugiandosi ai piedi di un altopiano, dove ora si trova la città di Ethedan.

I sopravvissuti hanno condotto una vita frugale, nascondendosi nelle caverne, per evitare le pattuglie dell'esercito che li stavano cercando. Intanto l'impero aveva difficoltà a mantenere l'insediamento di Sernost, e la ripopolazione delle altre città abbandonate, questo perché l'isola era vista dalla gente come un luogo maledetto, ed erano pochi i coloni disposti ad insediarvisi. Intanto la popolazione di Ethedan creasceva, lentamente, anche grazie alle incursioni nelle colonie imperiali per diffondere il vampirismo. Le sparizioni di coloni hanno ulteriormente contribuito alla cattiva reputazione dell'isola, e lentamente le popolazioni delle varie città sono state spostate a Sernost. Le attenzioni imperiali all'isola sono andate scemando, a causa dei costi per mantenere le colonie, ed alla mancanza di coloni volontari. Ethedan invece continuava a crescere, soprattutto grazie all'immortalità di buona parte dei suoi abitanti. Nonostante la loro natura, i vampiri di Ethedan, visto il numero esiguo della popolazione rimasta umana, si sono imposti di nutrirsi solo di animali, e di proteggere i compagni umani. Questa convivenza pacifica tra le due razze ormai distinte, ed il nemico comune, ha contribuito all'unità della città. 

Per circa 4 secoli quella che era a tutti gli effetti una città stato ha prosperato, espandendosi nella zona circostante, soprattutto verso sud, respingendo gli invasori mutati. Un'intensificazione delle tempeste astrali ha portato ad una nuova epidemia, più violenta che si è diffusa anche a nord, oltre il mare, e scatenando disordini in tutti i territori dell'Impero. Gli abitanti di Vagra ne hanno approfittato per scacciare le forze imperiali, notevolmente ridotte in numero e prendere definitvamente il controllo di Vagra. Con la presa di Sernost, si sono proclamati una nazione indipendente, togliendo l'isola al controllo imperiale. Successivamente alla proclamazione, sono stati inviati emissari in tutte le capitali provinciali di Meridia, chiedendo di essere riconosciuti come nazione indipendente. Dei 13 nobili costituenti, in 4 ne hanno riconosciuto l'indipendenza, in cambio di un supporto militare e diplomatico in caso di necessità. Questi 4 nobili erano i capi di casati molto influenti nell'impero: la famiglia Sundvik, il cui capostipite era governatore di Norlyn e primo membro del consiglio della provincia, che temevano un'attacco da Tedara, e aspiravano all'indipendenza, la famiglia dei duchi Vulic, che controllavano il territorio più vicino all'isola di Vagra, i quali temevano un eventuale invasione, il capostipite della famiglia Silrey, principe di Carenia, il quale cercava appoggi per ascendere al trono, ed il governatore di Medor, Kaalios Gaunn, attirato dalle possibilità ad aprire i commerci ed espandere la propria influenza a sud. 

Con l'indipendenza, la neonata Repubblica Scarlatta ebbe un periodo di relativa stabilità, durante il quale venne regolamentato il governo della nazione: ogni 6 anni, tutti i cittadini umani e non, di una certa ricchezza, dovevano eleggere un consiglio composto da 3 rappresentanti umani e 3 rappresentanti vampiri. Inoltre ogni governatore delle città doveva nominare un umano ed un vampiro che rappresentassero la loro regione al senato di Ethedan. Il consiglio ed il senato poi nominavano un cancelliere che presiedeva entrambi gli organi. Oltre all'organizzazione politica, è stata formalizzata la creazione e l'organizzazione di un esercito, e di una marina militare.

=== Shorlea

==== Figlie di Talena

Figlie di Talena													
La fiducia nel progresso tramite lo sviluppo delle arti magiche e non, è stata l'inziale idea che ha portato Talena, antica arcimaga, a creare la propria fazione. Stabilita nella parte più ad est di Talenalia, questa società matriarcale capitanata da una regina è specializzata nell'approfondire le conoscenze delle arti magiche e trarne beneficio. Se inizialmente l'intento di Talena era di progredire senza aiuti da altri regni o entità, una sua discendente molte generazioni dopo ha "ceduto" ed eventualmente ha fatto ricorso a patti e accordi con esterni principalmente malvagi, perché il loro potere potesse accrescere. La popolazione nonostante tutto non risente troppo di questi infausti accordi e a meno di non essere altolocati ed avere contatti con la cerchia di nobiltà che ha a che fare con la famiglia reale, la malvagità che permea questo governo non è dannosa, e anzi la vita è relativamente piacevole e pacifica. La magia è diffusa e spesso intrinseca in molti oggetti di uso comune, in un modo analogo a come la tecnologia del regno di Balir ha portato benefici in ogni casa, ma questo non impedisce che essa sia tenuta sotto controllo dal regno.

==== Ignariti

Coloro che credevano nella forza fisica, cercavano un luogo che creasse degli individui forti e robusti, temprati dalla spietatezza della natura incontrastata. Esiste un monte nell'estremo occidente di Talenalia che è in un perenne clima invernale feroce, in particolare quando Mastralis è in inverno: quale migliore luogo per temprare i corpi e selezionare gli individui più resistenti? Questo è il credo di Ignar, il fondatore di questo regno volontariamente posto forse nel luogo peggiore del piano. A cavallo fra Talenalia e l'isola di Marelia collegate dal mare ghiacciato, questo regno è demograficamente parlando molto piccolo. Sono poche le persone che sopravvivono. Questa selezione naturale però produce quelli che sono i migliori combattenti, robusti e stoici, le cui gesta vengono narrate in lungo e in largo e addirittura temute dallo stesso impero. Se gli altri regni hanno eserciti che contano sul numero dei propri soldati, qui si corona il detto "pochi ma buoni", un piccolo gruppo di questi uomini può fare la differenza.	
Il freddo è la loro maledizione ma anche il loro miglior alleato: rende quasi impossibile lo sviluppo di tecnologia, la coltivazione, riduce l'allevamento a quei pochi animali adatti a tale clima, e costringe questi popoli ad essere briganti e vivere di razzie alle spese delle nazioni limitrofe che li sopportano a malapena e non indicono guerra per non sbilanciare quello che da tempo immemore è noto come l'equilibrio di Talenalia: la paura di diventare nazioni indebolite dalla guerra, facili prede per il potente impero Adahim. 

==== Regno di Balir

Il regno di Balir è l'unione di coloro che credeva nel potere dello sviluppo tecnologico, e decisero di renderlo il fulcro della loro nazione.													
Proprio per questo si può dire che questo sia un regno molto diverso da tutti gli altri. I visitatori raccontano di aver visto meraviglie dell'ingegno che 													
farebbero impallidire chiunque.													
La tecnologia ha cercato di infondersi in tutti gli aspetti della vita di tutti i giorni e non solo nel lato della potenza militare.													
Balir la capitale, che da il nome al regno, è infatti un gioiello del progresso da loro raggiunto: al suo interno vi sono veicoli a vapore pubblici e personali, 													
industrie  automatizzate, rete fognaria, acquedotto a pressione e acqua calda in moltissime case.													
Sempre loro opera è stata anche la rete ferroviaria che arriva anche a collegare le varie città del regno, e anche alcuni dei regni confinanti che gli hanno													
concesso la costruzione per il bene del commercio.	

==== Legione di Tilgan

Tilgan, ex-generale agli ordini diretti dello stesso Adahim, rifiutò di prestare servizio presso i discendenti del suo defunto imperatore: anche lui come molta della popolazione, lo vedeva come essere immortale e prese la sua morte come se quell'entità fin'ora avesse preso in giro non solo lui ma tutto il popolo.
Divenne non solo disertore ma fù il primo capo della ribellione. Molti dei suoi subordinati che vedevano in lui un uomo giusto, oltre che un generale, decisero di seguirlo, come anche fece una buona fetta di popolo. Era alla stregua di una guerra civile alla fine, e Tilgan prendendo l'esempio dai draghi, capì che la scelta migliore era quella dell'esilio, già ordinato ufficialmente dal nuovo imperatore.
Uomo tutto d'un pezzo, ma di estrazione militare, la sua mentalità era marziale e non troppo flessibile: fra le varie proposte di come avrebbero dovuto	crescere come popolo, Tilgan non era dell'intento di cambiare il loro modo di vivere. Se gli altri decisero di andarsene per seguire le loro ideologie, Tilgan da conservatore decise di gestire il popolo che lo aveva seguito così come avrebbe gestito un esercito nella sua terra natia.
Nacque così la sua Legione, una nazione militare stabilitasi nell'isola più vicina al vecchio impero che li aveva esiliati, erta come a bastione difensivo nel caso che l'impero decidesse di schiacciare coloro che avevano scelto di non seguirli.	

=== Valentar

==== Vhir

L'isola di Valentar non è propriamente un regno come i vari regni delle altre terre, si tratta più che altro di un'isola che ospita il volontario esilio di quasi tutti i draghi che abitavano il piano. Il celestiale Adahim dominava su di loro, ed in particolare sul suo ibrido appositamente creato, l'unione fra due progenie di draghi dalla natura completamente opposta (Tiamat e Bahamut): questo dominio era possibile grazie a potenti magie infuse in alcuni artefatti da lui creati. I draghi soggiogati in una sorta di torpore non opposero resistenza, e si lasciarono ad ogni																					
forma di sfruttamento da parte dell'impero e tutti i suoi appartenenti, popolazione inclusa: cavalcature da guerra, bestie da soma o anche cavie per esperimenti. Tutto fino a quando il celestiale morì.																					
Alla sua morte, sebbene un discedente esistesse già per ereditare da lui il controllo di Arquel, del regno e dei draghi, per qualche ragione il dominio artificiale sulla volontà dei draghi svanì permettendo ad essi di accorgersi di quello che veniva loro imposto e dando inizio alla loro ribellione: 																					
per qualche giorno i draghi più violenti e rancorosi cominciarono a seminare distruzione nell'impero, che di certo non si aspettava l'improvvisa ribellione della sua più preziosa risorsa di quel momento, e subirono grandissime perdite.																					
I draghi decisero quindi di andare a vivere in esilio in una nuova terra che avrebbero tenuto per se giurando che mai più nessun regno li avrebbe domati così com'era successo, così portando con sè vari artefatti di grande potere e anche un piccolo gruppo di persone che aveva																					
dimostrato di non volere i draghi come servi. Attraversarono il grande mare e trovarono l'isola di Valentar, reputandola adatta al loro scopo vi si insediarono fondando la città libera di Vihr abitata da draghi e da quei pochi che li avevano seguiti volontariamente.																					

Nello scorrere dei millenni l'isola non è cambiata molto. Qualunque tentativo di assalto è stato prontamente represso dalla grande potenza dei draghi, che accettano solo il passaggio di viandanti o di nuovi pellegrini che decidono di stabilirsi in quell'isola.																					
In particolare molti disertori spesso cercano nell'isola un luogo al sicuro da qualsiasi esercito possa volere di tornare a prenderli, tuttavia non tutti sono reputati degni di soggiornare dagli stessi draghi che vedono in cattiva luce quelli che anche in passato abbiano fatto parte di una																					
forza armata, a causa del dubbio che non siano spie o infiltrati.																					

==== Londaure 

=== Vallea

==== Adahimia

Impero di Adahim																				
L'impero Adahim nasce come la iniziale casa del celestiale che ha creato il piano d'esistenza, e da lui ne prende il nome. La sua idea era quella di creare uno spazio tutto per se dove poter regnare come l'unico essere divino per il tempo rimanente della sua vita: pertanto forma i vari continenti e ne prende uno come dimora per se e il suo popolo. La creazione del piano è datata a circa 5000 anni prima delle vicende attuali, e lui ci visse per circa 300 anni, durante i quali non successe nulla di particolarmente eclatante. I popoli da lui creati o portati hanno vissuto in tranquillità, ma alcuni in paura della sua forza. Oltre ad essere lui stesso un celestiale di grande potenza, aveva creato per il suo impero una serie di elementi che sugellavano il suo dominio: disponeva di molti artefatti dal potere enorme, che gli davano il controllo dei draghi Alla sua morte, molte vicende si susseguirono: i draghi si ribellano e l'ibrido instabile torna nelle forme originali delle progenie da cui era stato creato. Come atto finale della loro ribellione oltre ai danni causati dalla loro ira, vi è la loro secessione ed esilio nell'isola vi Valentar, nella quale hanno portato gli artefatti che permettevano a Adahim di controllarli e alcuni degli umani che si erano presi cura di loro. La successione al trono andò a suo figlio, primo imperatore Aasimar nato dall'unione del celestiale con un'umana: ereditò il pieno controllo sulla totalità dell'impero e sull'isola volante di Arquel. A differenza del padre, che incorporava tutte le virtù dei celestiali, lui era imperfetto e non riuscì a mantenere lo stesso controllo che esercitava il padre. In particolare la morte di una quasi dinività causò lo scetticismo generale di chi vedeva nel celestiale un tiranno o un'entità divina eterna da venerare. Tutti coloro che per questi motivi cominciarono a lamentarsi e/o rivoltarsi vennero soppressi inizialmente e esiliati i rimanenti. Da allora l'impero ha dovuto gestire la mancanza dei draghi, che erano una forza non solo militare, ma permetteva loro di dominare i cieli anche come trasporto civile e mercantile. Si adattarono ad utilizzare molti animali e bestie volanti, che tengono sotto scacco i cieli da qualsiasi attacco proveniente dall'alto e dal basso.	Proprio per questo sono state fondate le città sulle vette delle montagne più alte, che oltre ad essere punto di sosta per i viaggi, fungono anche da strutture di addestramento degli avieri e delle bestie usate per il volo.	Nell'impero per questo il volo è abbastanza comune, nonché si tratta di un grande vanto rispetto agli altri regni. Le città principali dell'impero si trovano nelle grandi vallate racchiuse dall'enorme catena montuosa dalla Fauce: molte città sono fiancheggiate da una o più fortezze di solito posizionate lungo la costa pronte a respingere attacchi provenienti dal mare. All'interno di queste città la vita si svolge normalmente, e nonostante sia un impero la popolazione risulta relativamente contenta e vive bene. Arquel:	In tutto il piano non esiste un qualcosa di più imponente di Arquel, l'isola volante. Casa della famiglia imperiale, ereditata da Adahim in persona che l'aveva creata per essere la sua dimora, ospita anche molti nobili e ricchi che possono permettersi un posto di spicco, letteralmente. Si tratta di un'enorme massa di terra e roccia pianeggiante che levita ad un'altezza di circa 4000 metri: si dice che sia tenuta in volo da un'artefatto incastonato al suo interno, e che risponde solo al primogenito discendente diretto della famiglia imperiale.Il clima è costantemente tenuto sotto controllo dallo stesso artefatto, che permette di vivere in un'eterna primavera, nonostante l'alta quota a cui si trova. La città di Arquel è sede del castello imperiale, e di una lussuosa e grandiosa città. L'isola è protetta in molti modi, tanto da essere considerata una fortezza a tutti gli effetti. Prima protezione è data semplicemente dall'altezza e la difficoltà di raggiungerla. Tutti i mezzi aerei sono tenuti sotto controllo dall'eccezionale forza aerea dell'impero, e per chi non vola, nel mare sottostante vi sono delle fortezze-stazioni dotate di ascensori che sollevano visitatori e merci. Sull'isola sono presenti forze armate e magiche d'elite: solo i migliori possono avere il privilegio di difendere il cuore dell'impero da minaccie esterne, ed essere ricompensati di conseguenza. Infine sono presenti molte strutture che all'apparenza sono dei mulini a vento, ma che in realtà si tratta di torri di difesa: ospitano armi d'assedio e fungono da generatori eolici che permettono il funzionamento dell'attrezzatura meccanica della città, fra cui gli ascensori.

== Sulle divinità

Le divinità sono aspetti del piano astrale in grado di intercedere nel piano materiale. Sono connessi a quest'ultimo in quanto il numero di creature che credono nella loro esistenza, e che li adorano influisce direttamente sul loro potere. Le varie specie inoltre adorano aspetti diversi delle stesse divinità.

I draghi, i lucertoloidi ed i coboldi adorano quelli che loro chiamano 9 grandi dragoni, ovvero divinità basate sugli elementi, e sui colori dei draghi stessi. Queste divinità sono:

* Aazrelag, il grande dragone rosso, dio del fuoco, signore dei vulcani
* Avyumakra, il grande dragone bianco, dio del ghiaccio, signore dell'inverno e dei ghiacci
* Drogshul, il grande dragone dorato, dio del potere astrale, signore della magia
* Jotraanviir, il grande dragone marrone, dio della terra, signore delle montagne
* Levhithkron, il grande dragone blu, dio dell'acqua, signore dei mari
* Londrun, il grande dragone verde, dio della vita, signore di tutte le creature viventi
* Nehrothkras, il grande dragone azzurro, dio dell'aria, signore dei cieli
* Kaalvurn, il grande dragone nero, dio della morte, signore dei morti
* Rolaan, il grande dragone viola, dio del fulmine, signore delle tempeste

Gli elfi silvani hanno un pantheon diverso, adorano i vecchi dei elfici:

* Londuril, il primo tra gli dei, signore della vita e delle foreste
* Melios, il dio elfico del sole, del fuoco e della guerra
* Sillamen, dio della caccia ed in seguito della morte
* Kalantis, signore dei ghiacci e delle montagne
* Lameril, signore dei mari e della pioggia

Gli elfi alti rifiutano l'esistenza di  divinità, nonostante abbiano avuto una prova diretta della loro esistenza. Riconoscono l'entità che li ha creati come esseri molto potenti, ma alterabili e mortali. Inizialmente aderivano anch'essi allo stesso pantheon adorato dagli elfi silvani. Ma con l'avanzamento tecnologico della loro razza, hanno abbandonato la religione preferendo perdersi nella loro vanità e grandezza.

I nani, pur riconoscendo l'esistenza di altre entità divine, adorano Jornivaark, il loro padre creatore, che li ha plasmati dalla roccia, signore delle montagne e dei metalli, ed Aazrelra, la dea dei vulcani e del fuoco, signora della forgia. Hanno inoltre una terza divinità: Muzar, divinità della guerra e dei guerrieri.

Gli gnomi sono creature poco religiose, e sono privi di un loro pantheon. Generalmente gli gnomi si affidano alle religioni dei luoghi dove vivono, ma non è rado trovare gnomi, soprattutto maghi, che non vedono le varie divinità come tali, ma piuttosto come entità del piano astrale molto potenti.

Gli umani hanno diversi pantheon a seconda del luogo.

Gorlanos: Nel continente di Gorlanos, gli umani hanno inizialmente adottato una religione politeista, che ha visto il numero di divinità ridursi fino ad arrivare a 5 divinità principali: 
* la Madre
* il Vecchio
* l'Amante
* l'Operaio
* il Soldato

Queste 5 divinità rappresentano per gli umani di Gorlanos i 5 elementi che governano la vita di ogni uomo: la Madre rappresenta la nascita, la vita e la famiglia; il Vecchio rappresenta la conoscenza, la magia e la morte, l'Amante rappresenta l'amore, la felicità ed il piacere, l'Operaio rappresenta il lavoro, la fatica e le arti ed il Soldato rappresenta la fedeltà al proprio signore, la guerra e la disciplina.

Adahimia: Nel continente di Vallea ci sono diversi culti, ma quello principale è costituito da un unico dio, chiamato Vernal, e del suo prescelto, l'Imperatore visto come un semidio. 

Elelia: Nell'isola di Elelia, il culto principale è quello di Vernal, ma non riconoscono l'imperatore di Adahimia come autorità divina.

Ignariti: la religione degli ignariti, a causa delle loro razzie ha preso molto dalle religioni delle altre popolazioni: la popolazione ha un pantheon composto da due divinità principali che si scontrano in un'eterna lotta: la dea Sigrana, il cui culto prende dalla Madre, Vernal e Londrun, e dall'altra parte Tormigron, signore della morte e del ghiaccio. 

Un caso particolare sono gli orchi: un detto comune in Adahimia recita: "ogni orco ha due divinità: se stesso ed il suo capo". Gli orchi infatti non hanno mai considerato l'idea di entità divine, e nella società orchesca dove i più deboli vengono oppressi, ogni membro si considera al di sopra di quelli più deboili di lui, mentre cercherà sempre di guadagnarsi la "benevolenza" del proprio capo, ovvero farà di tutto per non farsi uccidere dal suo superiore. Gli ogre invece sono semplicemente troppo stupidi per avere un lato "spirituale". I goblin invece adorano quello che loro chiamano il Goblin Nero, un dio non propriamente malvagio, ma che promuove l'insurrezione dei goblin contro i loro padroni orcheschi. Questo culto ovviamente non è ben visto dagli orchi, che cercano di estinguerlo.

[cols="3", options="header"]
|===
^.^|Nome			^.^|Posizione				^.^|Nazione
^.^|Norlyn			^.^|Meridia					^.^|Regno libero del sottosuolo, TLDNO
^.^|Laria			^.^|Meridia					^.^|Impero di Meridia, TLDNO
^.^|Carelian		^.^|Meridia					^.^|Ribelli, TLDNO
^.^|Tedara			^.^|Arstelda				^.^|Città stato di Tedara, TLDNO
^.^|Ederla			^.^|Meridia					^.^|Ducato Vulic, TLDNO
^.^|Medor			^.^|Lunia					^.^|Gilda della Fenice / Confederazione Commerciale, TLDNO
^.^|Sernost			^.^|Vagra					^.^|Repubblica Scarlatta, TLDNO
^.^|Ethedan			^.^|Vagra					^.^|Repubblica Scarlatta, TLDNO
^.^|Vihr			^.^|Valentar				^.^|Valentar
^.^|Londaure		^.^|Valentar				^.^|Elfi Silvani
^.^|Krater			^.^|Pilastro di Krater		^.^|Pilastri di Arhada
^.^|Yas				^.^|Marelia					^.^|Regno di Ignar
^.^|Balir			^.^|Talenalia				^.^|Regno di Balir
^.^|Garenia		 	^.^|Talenalia				^.^|Regno di Balir
^.^|Exeter			^.^|Talenalia				^.^|Regno di Balir
^.^|Opensha			^.^|Talenalia				^.^|Regno di Balir
^.^|Lingmell		^.^|Talenalia				^.^|Regno di Balir
^.^|Nuxvar 			^.^|Talenalia				^.^|Regno di Balir
^.^|Threlkeld		^.^|Talenalia				^.^|Regno di Balir
^.^|Hankala			^.^|Talenalia				^.^|Regno di Balir
^.^|Aynor			^.^|Talenalia				^.^|Regno di Balir
^.^|Fernsworth		^.^|Talenalia				^.^|Regno di Balir
^.^|Nantgarth		^.^|Talenalia				^.^|Regno di Balir
^.^|Blaena			^.^|Talenalia				^.^|Regno di Balir
^.^|Penshaw			^.^|Talenalia				^.^|Regno di Balir
^.^|Ilebur			^.^|Talenalia				^.^|Regno di Balir
^.^|Ar-Olmore 		^.^|Talenalia				^.^|Regno di Balir
^.^|Swindmore		^.^|Talenalia				^.^|Regno di Balir
^.^|Kaiven			^.^|Talenalia				^.^|Regno di Balir
^.^|Grilab			^.^|Talenalia				^.^|Regno di Balir
^.^|Olusien			^.^|Talenalia				^.^|Regno di Balir
^.^|Calibard		^.^|Talenalia				^.^|Regno di Balir
^.^|Urfao			^.^|Talenalia				^.^|Regno di Balir
^.^|Pimmalin		^.^|Talenalia				^.^|Regno di Balir
^.^|Amaril			^.^|Talenalia				^.^|Figlie di Talena
^.^|Harailin		^.^|Talenalia				^.^|Figlie di Talena
^.^|Casserin		^.^|Talenalia				^.^|Figlie di Talena
^.^|Nilnedell		^.^|Talenalia				^.^|Figlie di Talena
^.^|Isil Galas		^.^|Talenalia				^.^|Figlie di Talena
^.^|Colthyr			^.^|Talenalia				^.^|Figlie di Talena
^.^|Deloriamd		^.^|Talenalia				^.^|Figlie di Talena
^.^|Thrulith		^.^|Talenalia				^.^|Figlie di Talena
^.^|Niomir			^.^|Talenalia				^.^|Figlie di Talena
^.^|Shyrlond		^.^|Talenalia				^.^|Figlie di Talena
^.^|Sil Gandil		^.^|Talenalia				^.^|Figlie di Talena
^.^|Belil Gadien	^.^|Talenalia				^.^|Figlie di Talena
^.^|Ril Galia		^.^|Talenalia				^.^|Figlie di Talena
^.^|Muriand			^.^|Talenalia				^.^|Figlie di Talena
^.^|Pil Gand		^.^|Talenalia				^.^|Figlie di Talena
^.^|Moriand			^.^|Talenalia				^.^|Figlie di Talena
^.^|Erynior			^.^|Talenalia				^.^|Figlie di Talena
^.^|Daerist			^.^|Talenalia				^.^|Figlie di Talena
^.^|Annuithang		^.^|Talenalia				^.^|Figlie di Talena
^.^|Nydalla			^.^|Valelya					^.^|Figlie di Talena
^.^|Calaril			^.^|Valelya					^.^|Figlie di Talena
^.^|Anorion			^.^|Valelya					^.^|Figlie di Talena
^.^|Veomyr			^.^|Elelia					^.^|Legione di Tilgan
^.^|Greyshel		^.^|Elelia					^.^|Legione di Tilgan
^.^|Damerel			^.^|Elelia					^.^|Legione di Tilgan
^.^|Vanniste		^.^|Elelia					^.^|Legione di Tilgan
^.^|Halvik			^.^|Elelia					^.^|Legione di Tilgan
^.^|Walden			^.^|Elelia					^.^|Legione di Tilgan
^.^|Estgal			^.^|Elelia					^.^|Legione di Tilgan
^.^|Asmont			^.^|Elelia					^.^|Legione di Tilgan
^.^|Pinepoint		^.^|Elelia					^.^|Legione di Tilgan
^.^|Brassfort		^.^|Elelia					^.^|Legione di Tilgan
^.^|Stillgarde		^.^|Elelia					^.^|Legione di Tilgan
^.^|Rachdale		^.^|Elelia					^.^|Legione di Tilgan
^.^|Coveford		^.^|Elelia					^.^|Legione di Tilgan
^.^|Tromwern		^.^|Elelia					^.^|Legione di Tilgan
^.^|Wildereach		^.^|Elelia					^.^|Legione di Tilgan
^.^|Gearsberg		^.^|Elelia					^.^|Legione di Tilgan
^.^|Kalgara			^.^|Elelia					^.^|Legione di Tilgan
^.^|Bralen			^.^|Vallea					^.^|Impero di Adahim
^.^|Bralenfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Asoar			^.^|Vallea					^.^|Impero di Adahim
^.^|Sedrim			^.^|Vallea					^.^|Impero di Adahim
^.^|Sedrimfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Artosk			^.^|Vallea					^.^|Impero di Adahim
^.^|Shaystorn		^.^|Vallea					^.^|Impero di Adahim
^.^|Shayfort		^.^|Vallea					^.^|Impero di Adahim
^.^|Grilming		^.^|Vallea					^.^|Impero di Adahim
^.^|Winglark		^.^|Vallea					^.^|Impero di Adahim
^.^|Conacon			^.^|Vallea					^.^|Impero di Adahim
^.^|Arquel			^.^|Vallea					^.^|Impero di Adahim
^.^|Caras Astra		^.^|Piano Astrale			^.^|Enclave astrale di Caras Astra
|===

== Cronologia

[cols="3", options="header"]
|===
^.^|Data 			^.^|Fazioni coinvolte	^.^|Avvenimenti
^.^|0				^.^|Tutto il piano		^.^|Creazione dell'intero piano d'esistenza. L'anno 0 è un anno estivo.
^.^|304 / -4741 	^.^|Impero Adahim		^.^|Morte di Adahim. Inizio della stirpe reale aasimar, rivolta ed esilio dei draghi
^.^|305 / -4740		^.^|Esilio dei Draghi	^.^|Insediamento dei draghi nell'isola di Valentar, fondazione di Vihr
^.^|2348			^.^|Teria				^.^|Fondazione di Teria
^.^|2709			^.^|Meridia				^.^|Fondazione dell'impero
^.^|2859 / -3186	^.^|Arhada				^.^|Catastrofe
^.^|4486 / -559		^.^|TLDNO				^.^|Colonizzazione delle prime isole del Mar d'Oro
^.^|4492 / -553		^.^|TLDNO				^.^|Fondazione di Laria. Il primo Imperatore di Meridia sale al trono
^.^|4495 / -550		^.^|TLDNO				^.^|Fondazione di Norlyn. Colonizzazione di Asteda. Le colonie abbandonate nel Mar d'Oro vengono ripopolate
^.^|4509 / -536		^.^|TLDNO				^.^|La Torre delle Catene è ultimata. Cresce l'importanza militare di Tedara
^.^|4531 / -514		^.^|TLDNO				^.^|Viene fondata la "Gilda dei mercanti del Mar d'Oro" a Medor. 
^.^|4540 / -505		^.^|TLDNO				^.^|Le voci della prosperità dell'Impero di Meridia portano nuovi coloni dalle terre dell'est. 
^.^|4543 / -502		^.^|TLDNO				^.^|Si inizia a parlare di un potente drago bianco sulla cima dell'Elmo degli Dei
^.^|4560 / -485		^.^|TLDNO				^.^|Il Culto del Drago Bianco si diffonde a Meridia
^.^|4667 / -378		^.^|TLDNO				^.^|Nascono Vorth e Petri, figli della sorella dell'Imperatore, che vengono affidati a due famiglie nobili: i Maren ed i Vulic.
^.^|4669 / -376		^.^|TLDNO				^.^|Nasce Lorin Fernim, figlio dell'Imperatore di Meridia.
^.^|4697 / -348		^.^|TLDNO				^.^|Muore l'Imperatore. Disputa per la successione tra Vorth, Petri e Lorin. Vorth Maren e Petri Vulic ricevono le città di Staria ed Ederla
^.^|4698 / -347		^.^|TLDNO				^.^|Il barone Vorth Maren riceve l'immortalità da un diavolo da lui evocato.
^.^|4700 / -345		^.^|TLDNO				^.^|Una malattia sconosciuta inizia a mietere vittime a Meridia. Evasione di massa dalla Torre delle Catene. Norlyn chiude tutti gli accessi alla montagna.
^.^|4701 / -344		^.^|TLDNO				^.^|Tedara è assediata da Vorth l'Immortale, con un esercito di immondi. I malati iniziano ad essere deportati a Vagra.
^.^|4704 / -341		^.^|TLDNO				^.^|Tedara cade e diventa capitale del nuovo regno. Vorth si proclama dittatore. L'epidemia continua a flagellare l'isola di Meridia
^.^|4706 / -339		^.^|TLDNO				^.^|Il numero di nuovi infetti inizia a scendere. Primi insediamenti ad Ethedan e Silverfall.
^.^|4707 / -338		^.^|TLDNO				^.^|Funzionari imperiali riferiscono di una repubblica nell'isola di Vagra. Azug ed Icta annesse al Ducato Vulic.
^.^|4709 / -336		^.^|TLDNO				^.^|L'epidemia è completamente scomparsa. La Gilda dei Mercanti del Mar d'Oro acquista le isole ad est di Meridia. Nasce la Confederazione Commerciale
^.^|4710 / -335		^.^|TLDNO				^.^|L'Impero concede alla città di Norlyn terre e sovranità in cambio di pace ed accordi commerciali. Viene fondata Cudir.
^.^|4712 / -333		^.^|TLDNO				^.^|Sindan è annessa al Ducato. Accordo di pace tra Impero e Ducato. Nasce Ladica Vulic. Accordi commerciali tra Impero e Confederazione.
^.^|4732 / -313		^.^|TLDNO				^.^|Ladica si ammala e viene deportata a Vagra. Primi contatti con la Repubblica dei Senza Luce.
^.^|4735 / -311		^.^|TLDNO				^.^|Ladica entra a far parte del consiglio dei sette della Repubblica. Il Ducato va a suo fratello. Fondazione di Nagastan.
^.^|4830 / -216		^.^|TLDNO				^.^|Muore il governatore di Carelian. Iniza la ribellione. Il Mare di Vagra è infestato da pirati ribelli. Viene chiamato Mar dei Relitti.
^.^|4832 / -214		^.^|TLDNO				^.^|Carelian è assediata. L'esercito imperiale è attirato nella Barriera Verde e massacrato. I pirati razziano e bruciano la città di Ledel.
^.^|4958 / -87		^.^|TLDNO				^.^|Muore l'ultimo Duca Vulic, senza eredi. Il trono passa alla sua antenata, Ladica, della Repubblica dei Senza Luce.
^.^|4960 / -85		^.^|TLDNO				^.^|Apparizioni di non morti nelle isole della Confederazione Commerciale. Intere popolazioni delle isole del Mar d'Oro scompaiono. Ladica abbandona Ederla.
^.^|4961 / -84		^.^|TLDNO				^.^|Medor è attaccata da un'armata non-morta. La popolazione viene completamente spazzata via. Gli elfi della grande foresta impazziscono e si ribellano a Norlyn
^.^|4961 / -84		^.^|TLDNO				^.^|L'armata non-morta scompare improvvisamente. Le isole del Mar d'Oro tornano com'erano, tranne per la popolazione.
^.^|4970 / -75		^.^|TLDNO				^.^|Medor viene gradualmente ripopolata. La Confederazione Commerciale rinasce, con il nuovo nome di Gilda della Fenice.
^.^|4974 / -71		^.^|TLDNO				^.^|La scoperta di giacimenti di pietre e metalli preziosi favorisce il ripopolamento dell'arcipelago del Mar d'Oro. Fondazione di Nuova Ledel.
^.^|4980 / -65		^.^|TLDNO				^.^|Guerra fra la Gilda della Fenice e l'Impero di Meridia per il controllo del Mar d'Oro.
^.^|4996 / -49		^.^|TLDNO				^.^|La flotta imperiale viene definitivamente sconfitta al largo di Boria.
|===
