= Razze senzienti

[cols="3", options="header"]
|===
^.^|Razza			^.^|Descrizione																	^.^|Magia			
^.^|Umani			^.^|Standard umani																^.^|D, E, S		x
^.^|Elfi Alti		^.^|Secondi creati al mondo, arroganti											^.^|D			x
^.^|Elfi Silvani	^.^|Elfi "buoni", guardiani della natura										^.^|D, E		x
^.^|Elfi Astrali	^.^|Elfi alti che hanno abbandonato il piano materiale e vivono nell'astrale	^.^|D			x
^.^|Driadi			^.^|Silvani che reincarnano lo spirito					  						^.^|E,			x
^.^|Goblin			^.^|Piccoli orcoidi intelligenti, affini alla magia								^.^|D, E		x	
^.^|Orchi			^.^|Orcoidi di taglia media, poco intelligenti									^.^|S			x
^.^|Ogre			^.^|Orcoidi grossi, quasi privi di intelligenza									^.^|X			x
^.^|Lucertoloidi	^.^|Draconidi bipedi, affini al sangue e al piano astrale						^.^|D, S		x
^.^|Coboldi			^.^|Piccoli draconidi bipedi che adorano i metalli preziosi 					^.^|E			x
^.^|Draghi			^.^|Quadrupedi alati simili a felini, affini agli elementi						^.^|D, E		x
^.^|Viverne			^.^|Draconidi alati bipedi, poco intelligenti									^.^|X			x
^.^|Nani			^.^|Standard nani																^.^|E			x
^.^|Gnomi			^.^|Piccoli umanoidi, molto intelligenti, grandi accademici						^.^|D, E, S		x	
^.^|Vampiri			^.^|Non morti che migliorano in capacità fisica col tempo						^.^|D, E, S		x	
^.^|Aviani			^.^|Elfi alati, vivono distaccati dal mondo										^.^|S			x
^.^|Mezzosangue		^.^|Uomini-bestie, mezz'orchi e mezzi draghi									^.^|D, E, S		x
^.^|Demoni			^.^|Manifestazioni meteriali delle emozioni, e maghi che perdono il controllo	^.^|E			x
^.^|Guardiani		^.^|Manifestazioni meteriali delle emozioni, e maghi che si distaccano dal mat	^.^|D			x
^.^|Divinità		^.^|Riflessi astrali delle credenze del piano materiale, e emozioni				^.^|D, E, S		x
^.^|Semidei			^.^|Creature del piano materiale con discendenza divina							^.^|D, E, S		x
|===	

* Umani: Razza che, con l'aiuto di Londrun si è distinta dai primati, formando società tribali e dimostrando grande capacità di adattamento. Col passare del tempo, dall'isola di Vihr sono migrati e si sono spostati in tutti i continenti, ma il principale gruppo di umani si è stabilito nell'isola di Vallea. Insediamenti umani si trovano principalmente in Vallea, dove è stato formato l'impero, a nord, nel continente di Gorlanos, e Talenalia.

* Elfi Alti: Creati da Londrun in un'era in cui i primi umani iniziavano a distinguersi dai primati, inizialmente erano creature immortali, ma dopo la catastrofe che li ha decimati, assieme alla distruzione del continente di Arhada sono stati puniti da Kaalvurn, che li ha privati della loro immortalità. Poco prima della catastrofe, un gruppo di elfi si è ribellato, e si è stabilito nelle varie foreste  del mondo, soprattutto nel continente di Gorlanos, deidcandosi alla protezine della natura, formando una razza separata, gli elfi silvani. Oggi gli elfi alti vivono in media 3 o 4 secoli, e sono dediti alla magia ed alle arti: non ci sono al mondo orefici, artisti o architetti migliori di loro. La loro cultura estremamente raffinata, unita alla loro iniziale immortalità, li ha resi arroganti e superbi, e la perdita della loro immortalità li ha resi più ostili verso le altre razze, soprattutto i mezzosangue e gli aviani, i quali ricordano loro della catastrofe che li ha portati alla loro condizione attuale. Esteticamente si presentano come creature alte quanto un umano, con lineamenti più snelli e longilinei, e movimenti più aggraziati; la caratteristica principale che li distingue dagli umani però sono gli occhi, che hanno tonalità che vanno dal giallo all'azzurro, passando per il blu, il viola, il rosso e l'arancione. Altra caratteristica distintiva delle razze elfiche sono le orecchie, che terminano a punta.

* Elfi Silvani: Inizialmente Elfi Alti che popolavano la città-tempio di Yle Thalor e le foreste sacre intorno ad essa, con il passare del tempo si sono lentamente trasformati in protettori della foresta stessa, e delle creature che vi abitavano. La foresta infatti era considerata come la culla della specie elfica, il luogo in cui Londrun ha creato i capostipiti della razza. Con il degenerare della società elfica, verso un uso sfrenato e sconsiderato della magia unita alla tecnologia, e l'idea che essendo stati creati "perfetti", il mondo fosse loro da sfruttare come preferivano, i fedeli di Londrun si sono ribellati, in un disperato tentativo di riportare all'ordine la società. Questa guerra però li vide spazzati via, la foresta venne abbattuta quasi del tutto, ed il grande tempio di Londrun a Yle Thalor saccheggiato e bruciato. In pochi riuscirono a fuggire, verso l'isola di Valentar, dove hanno fondato una nuova città: Londaure, situata sulla punta sud occidentale dell'isola. Lì conducono un'esistenza dedita alla protezione della foresta e degli esseri viventi che popolano l'isola e la proteggono anche dalle varie incursioni di orchi e mezzosangue che arrivano da Arhada. Hanno come fine ultimo però quello di tornare alle rovine di Yle Thalor, e ricostruire la città. Col tempo hanno stabilito diverse enclavi nelle foreste del mondo, e sono generalmente tollerati dalle altre specie senzienti. Hanno ottimi rapporti con i nani di Norlyn, soprattutto per l'astio comune nei confronti degli Elfi Alti e delle razze impure. Fisicamente somigliano molto agli altri elfi, tranne che per la carnagione più scura e la struttura corporea più simile ad un umano. La maledizione di Kaalvurn ha colpito anche loro, ma, grazie alla loro devozione, hanno la possibilità, alla morte, di reincarnare lo spirito in quelli che a tutti gli effetti sono elementali della natura: Driadi.

* Elfi Astrali: Potenti maghi elfici che hanno dedicato tutta la loro esistenza a tenere un equilibrio tra magia e vita materiale: invece di distaccarsi completamente dal proprio corpo, sono riusciti a trascendere l'esistenza dal piano materiale a quello astrale. Raggiungere ed essere ammessi a Caras Astra è l'aspirazione più grande di molti studenti delle varie accademie di magia sparse per il mondo, ma in molti falliscono, soprattutto membri delle altre razze. Buona parte della popolazione di Caras Astra infatti è composta da Elfi Alti, mentre le atre razze sono presenti, ma di rado superano la decina di membri. Gli Astrali, essendosi distaccati quasi completamente dal piano materiale, rinunciano a qualsiasi fedeltà verso le varie razze o nazioni, concentrandosi nella meditazione e nel cercare di unire il corpo e lo spirito. Un'altra funzione importante che svolgono è quella di aiutare i guardiani, cercando e distruggendo i demoni sia sul piano materiale che astrale.

* Driadi: Quando un Elfo Silvano percepisce che la sua vita è prossima alla fine, in genere oltre i 350 anni, può scegliere se accettarne la fine, o sottoporsi ad una prova: si dovrà recare al tempio di Londrun nella città di Londaure, ed offrirsi come eterno protettore della vita. Se la sua offerta viene accettata dal Gran Sacerdote, verrà tenuta una cerimonia funebre in suo onore, ed egli verrà scortato alle rovine del tempio di Yle Thalor, dove verrà abbandonato. L'aspirante protettore entrerà in meditazione nella foresta, cercando di comunicare con le varie creature che la popolano. Se riesce ad entrare in contatto con la vita della foresta, la foresta stessa lo accoglierà come parte di essa. Lo spirito dell'elfo si unirà al proprio riflesso astrale, mentre il corpo muta: la pelle diventa più scura e dura, simile in sembianze al legno; i tratti facciali si fanno più accentuati, scompaiono gli organi riproduttivi, ed i capelli. Gli occhi diventano bianchi, e la bocca si chiude. Il naso rimane, ed è attraverso quello che il driade respira. Perde il bisogno di mangiare, trae infatti nutrimento dal terreno. Gli arti superiori si allungano, fino a sfiorare il terreno, e le dita diventano delle punte accuminate. Con il tempo, una volta che il driade si è adattato al proprio corpo, può controllarne lo sviluppo: in alcuni casi infatti un driade può presentare delle corna, o 4 zampe, o 4 braccia, e così via; il cambiamento che avviene più spesso però è il ripristino dell'aspetto che l'elfo aveva in vita, tramite la crescita di fogliame dove una volta aveva i capelli, e dei tratti facciali più simili a quelli che aveva in vita. Una volta terminata la rinascita, il driade può scegliere dove servire, in genere ritorna al suo luogo natio. Il driade è in grado di comunicare telepaticamente con qualsiasi creatura senziente, ed a livello empatico con animali e piante. Ciò significa che percepisce le emozioni di tutte le creature intorno a lui, ed ha un buon controllo sugli animali. A volte questa connessione indesiderata può portare ad un sovraccarico emotivo, ad esempio durante una devastazione del luogo che sta proteggendo, e può causare la temporanea o permanente follia del driade.

* Orcoidi: Le specie orchesche rientrano tra le prime forme di vita create, e possedevano un'intelligenza molto basilare. Questi proto-orchi mostravano una grande capacità di adattamento all'ambiente, e notevole aggressività, che ha permesso loro di sopravvivere alle prime fasi del mondo. L'organismo degli orcoidi è un qualcosa di unico, in quanto sembra che le dimensioni siano correlate con l'intelligenza della creatura. Sono stati impiegati dagli elfi come schiavi, e dopo secoli di riproduzione selettiva di questi animali intelligenti, si sono distinte 3 tipologie di orcoidi.
** Goblin: Il goblin è il più piccolo, ed il più intelligente degli orcoidi. Alti circa quanto uno gnomo, hanno la pelle di un verde che varia a seconda dell'età della creatura, i lineamenti sono pronunciati, soprattutto il naso ed il mento. Sono gli unici membri della specie che possono praticare il distaccamento astrale. Molti elfi erano soliti tenere goblin come animali da compagnia, o come servi di studiosi e maghi. In rari casi hanno servito anche come assassini e spie. Dopo la catastrofe, molti di loro sono stati abbandonati a loro stessi, altri si sono ribellati contro i loro padroni, ed hanno iniziato a formare piccole società tribali. Come gli altri membri della specie si sono diffusi in tutto il mondo, dove infestano soprattutto il sottosuolo. La specie orchesca non ha subito grosse mutazioni dalla catastrofe, ma piuttosto ha ottenuto un'accentuazione delle caratteristiche che distinguevano le loro razze.
** Orchi: L'orco è una creatura relativamente stupida, che si aggira intorno ai due metri di altezza, dalla pelle verdastra, e dalla mandibola pronunciata. Buona parte del cranio dell'orco è formato dal volto, largo e schiacciato, mentre il cervello è poco sviluppato. L'orco non possiede un'intelligenza sviluppata come il goblin, ma comunque è in grado di fare ragionamenti, seppur semplici, e parlare. Il fisico di un orco però è molto potente. Ha una struttura muscolare molto sviluppata, soprattutto nella parte superiore. Questo li ha resi guardie del corpo abbastanza buone, nonostante comunque covassero un certo risentimento nei confronti dei loro padroni. Venivano inoltre utilizzati come manovali: erigevano case, mura ed infrastrutture. 
** Ogre: L'ogre è una versione più grossa, violenta e stupida di un orco. Arrivano fino a 3 metri di altezza, con una muscolatura possente che li ha resi ideali per lavori pesanti. La testa è piccola, e la spessa pelle di un verde scuro. Gli ogre non riescono a praticare la magia, e sono quasi del tutto immuni all'energia astrale. Sono in grado di parlare, nonostante il loro linguaggio sia articolato come quello di un bambino di 5 anni. Hanno avuto un impiego limitato nella società elfica, vista la loro stupidità, ed instabilità, ed oggi ce ne sono molto pochi. Come gli altri orcoidi, si sono insediati in ogni parte del mondo, costruendo rudimentali accampamenti dai quali lanciano raid agli insediamenti vicini.

* Lucertoloidi: I lucertoloidi sono stati creati dopo i coboldi, e rappresentano i primi tentativi di creare delle creature draconiche affine agli elementi. Come dimensioni sono paragonabili ad un umano. La testa è simile a quella di un serpente, gli arti anteriori, come nei coboldi, sono più lunghi, anche se più proporzionati rispetto ai loro cugini. Le mani ed i piedi terminano in dita artigliate, ed entrambe le estremità sono palmate. La pelle è squamosa, e come per i draghi, il colore varia a seconda dell'elemento a cui somigliano. A differenza dei draghi però, non hanno capacità di soffio o simili. Il colore della pelle ne determina le caratteristiche fisiche: i lucertoloidi azzurri sono in grado di muoversi più silenziosamente, e nascondersi meglio degli altri; quelli blu sono eccellenti nuotatori, e sono in grado di respirare sott'acqua; quelli bianchi resistono molto bene al freddo, e, anch'essi sono in grado di respirare sott'acqua. I lucertoloidi dorati sono gli unici capaci di utilizzare la magia; quelli marroni sono fisicamente più grossi, e molto più resistenti. I lucertoloidi rossi resistono al caldo molto bene, e sono ottimi combattenti. Quelli neri sono immuni a veleno e malattie, di cui hanno un'innata conoscenza. I lucertoloidi verdi sono in grado di rigenerarsi, ed hanno una conoscenza innata della natura tale da renderli ottimi guaritori; ed infine quelli viola sono molto più rapidi nei movimenti, e di gran lunga più astuti.

* Coboldi: I coboldi sono piccole creature draconiche intelligenti. Tendono ad essere più piccoli dei goblin, ed esili. La testa, simile a quella di un coccodrillo o alligatore, è dotata di una mandibola abbastanza potente per le dimensioni, e di denti piccoli ma affilati. I lunghi arti superiori terminano in 4 dita artigliate, e così anche i piedi. La pelle è squamosa, di colore biancastro sul ventre, mentre il dorso, gli arti e la testa hanno tonalità variabili, ma che in genere vanno dal verde al marrone-rossastro. Il coboldo possiede una rudimentale forma di intelligenza. Hanno un linguaggio complesso, e sono in grado di incanalare le proprie emozioni per lanciare magie. Col tempo il coboldo si è evoluto dall'essere una creatura che cammina su 4 zampe, ad una completamente bipede, in grado di creare ed utilizzare attrezzi rudimentali. Si trovano principalmente sull'isola di Valentar, ma anche nelle foreste dei continenti del nord. Sono attratti dai metalli e dalle pietre prezione, ed hanno una compulsione a rubarne il più possibile. Se minacciato un coboldo generalmente tenterà la fuga, a meno che non sia in un gruppo che ha il vantaggio numerico dalla sua parte.

* Draghi: I draghi sono stati creati come rappresentazione vivente degli elementi. Sono grossi quadrupedi alati, molto intelligenti, con un lungo collo ed una coda altrettanto lunga. A seconda del colore, si denota una particolare affinità ad un elemento, e delle caratteristiche fisiche variabili. La struttura di base però rimane sempre la stessa. Sono creature molto intelligenti, in grado di parlare. Solitamente sono neutrali nei confronti delle altre razze senzienti, e di rado attaccano deliberatamente. Alcune tipologie di drago instaurano persino dei rapporti con altre specie senzienti, soprattutto con gli Elfi Silvani, ma accade anche con umani, gnomi e nani.
** Azzurro: Un drago azzurro è un drago nato per volare. Ha una pelle sottile, composta da piccolissime squame, indistinguibili tra loro a meno che non si esamini la pelle da vicino, le ossa cave ed un corpo snello; è il più piccolo tra i draghi, ma anche il più veloce ed agile. Si nutre principalmente di uccelli, ma non è raro vederlo nuotare nei vari mari del mondo a caccia di pesci. A differenza della maggior parte degli altri draghi, è privo di armi a soffio. Le sue armi principali sono l'agilità, i denti e gli artigli affilati, ed una placca ossea molto dura alla fine della lunga coda, che utilizza come una lama. La colorazione varia dall'azzurro cielo al blu chiaro, a seconda dell'età dell'animale.
** Bianco: Un drago bianco è generalmente più grande di un drago azzurro, anche se non di molto. A differenza dei draghi azzurri però, sono più tozzi e robusti, con delle protuberanze ossee che escono dalle scaglie biancastre che li ricoprono, partendo dalla nuca, fino alla coda. Il loro corpo è coperto da scaglie simili a scudi, e sono gelidi al tatto. Le ali, meno sviluppate rispetto agli altri draghi, consentono un volo lento e goffo rispetto agli altri esemplari, ma comunque più veloce di un cavallo al galoppo. I draghi bianchi vivono nei luoghi più freddi del pianeta, come cime delle montagne o le distese ghiacciate tra marelia e talenalia. Si nutrono di qualsiasi cosa riescano a trovare, e sono noti per aver attaccato insediamenti di umanoidi vari, anche se quest'opzione viene considerata solo in casi di estrema necessità. Un drago bianco può sopravvivere per mesi senza cibo, entrando in uno stato di ibernazione. Se minacciato, il drago attacca con un'arma unica alla loro specie: soffia una nube d'acqua simile ad una nebbia finissima, che però è a temperature molto basse. Questo fa si che appena entri in contatto con un qualsiasi oggetto formi uno strato di ghiaccio, che rende la vittima incapace di muoversi, sigillandola in un blocco di ghiaccio.
** Blu: Il drago blu è l'esemplare che più si allontana dalla famiglia dei draghi: le zampe, più lunghe rispetto agli altri draghi, terminano in 4 lunghe dita artigliate e palmate, che li rendono eccellenti nuotatori. Il corpo è più simile ad un serpente seppur siano evidenti spalle e bacino, e le dimensioni sono simili a quelle di un drago azzurro. Le ali sono meno sviluppate rispetto agli altri draghi: il drago blu infatti non riesce a volare per periodi di tempo prolungati. La testa a forma di diamante nasconde due file di denti corti ma affilati, chiusi da una mascella capace di tranciare di netto un soldato in armatura con relativo cavallo, ed una cresta che percorre il drago per tutta la lunghezza. La colorazione varia dal celeste al blu notte, arrivando ad essere indistinguibile come colore da un drago nero negli esemplari più vecchi. Ci sono poche creature che attaccano deliberatamente un drago blu. Se attaccato sulla terra ferma o dalla superfice del mare, il drago usa la coda per atterrare o capovolgere in nemico, per poi balzargli addosso e dilaniarlo con artigli e denti, se invece il pericolo viene da sott'acqua, il drago prima affonda gli artigli anteriori sulla vittima, poi a seconda delle dimensioni di quest'ultima rispetto al drago, o l'avvolge e la stritola, o ne strappa le carni con gli artigli posteriori. Può anche capitare che una volta immobilizzata la vittima il drago prenda il volo e la faccia precipitare verso il suolo.
** Dorato (Oro): Il drago dorato è un drago imponente, dal collo lungo e gli occhi viola. È il drago con più capacità magiche, e di gran lunga il più raro. La loro pelle  è squamosa, ed alla nascita di colore bianco-giallastro. Con il tempo le squame iniziano ad ispessirsi ed acquistano un colore più acceso. Crescendo inoltre, le squame si coprono di una patina vitrea, che conferisce loro particolare lucentezza. La testa di un drago dorato è simile a quella del drago blu, ma un po più oblunga, e termina in una protuberanza ossea simile ad un becco. Due corna si distaccano dalla testa e formano una "S". In rari casi le corna possono a loro volta biforcarsi, ma succede solo agli esemplari più vecchi, ormai prossimi alla morte. Queste corna non hanno utilità difensiva, e sono presenti solo nei maschi. È estremamente raro che un drago dorato combatta, e se lo fa cercherà di portarsi a distanza per usare le sue capacità magiche. Se qualcosa però gli impedisce di allontanarsi, allora carica sfruttando la sua mole ed il becco come armi principali.
** Marrone: Un drago marrone è un drago di dimensioni ancora più grandi di un drago dorato. È coperto da una dura pelle coriacea sul ventre, di colore biancastro, mentre il resto del corpo è coperto di dure placche ossee, di un colore che va dal marrone-rossastro al marrone più scuro. Nonostante la mole imponente è sorprendentemente veloce, e le possenti ali gli permettono un volo prolungato, seppur lento ed impacciato; terminano inoltre in due lunghe protuberanze ossee simili ad artigli. Le grosse zampe terminano in 4 dita artigliate. Sono creature pacifiche, che si muovono di rado, ed attaccano senza provocazione ancora meno. Non è raro infatti osservare piccole tracce di vegetazione crescere sugli arti e sul dorso del drago. Si nutrono di qualsiasi cosa riescano a trovare, e riescono a digerire persino metalli e rocce, e sono formidabili predatori se necessario. Se minacciati attaccano cercando di schiacciare l'avversario con il loro stesso peso. Nel caso sia un avversario della loro stessa taglia, usano sia le ali che le zampe per attaccarsi all'avversario e dilaniarlo con gli artigli e le zanne. Nonostante sia possibile avvistarne ovunque nella terra ferma, soprattutto nell'isola di Valentar, è più comune trovarli ai piedi delle montagne.
** Nero: I draghi neri sono visti come portatori di morte e malattie da parte delle altre razze senzienti, ed in parte è vero. Il drago nero è di dimensioni simili ad un drago dorato, con delle scaglie taglienti che vanno dal grigio scuro al nero. La testa del drago nero è coperta di piccole corna affilate che culminano in due lunghe corna che piegano leggermente in avanti. I lunghi denti del drago spuntano dalla mandibola. Le ali culminano, come nel drago marrone, in due lunghi artigli. Dal collo partono poi delle placche ossee appuntite. In combattimento il drago può fare ricorso a due armi molto pericolose, oltre ai denti e gli artigli che ha sulle ali: sotto la sua lingua infatti vi sono due ghiandole che secernono veleno. Il veleno che sputa in questo modo, generalmente viene direzionato verso gli occhi della vittima, accecandola, permettendo così al drago di colpire con più sicurezza. Se ingerito o inalato il veleno porta ad una morte dolorosa che può sopraggiungere molto rapidamente, a seconda della creatura colpita. Alternativamente, il drago può soffiare fuori il veleno, coprendo un'area più vasta. La nube porta i risultati del veleno sputato, ma con un effetto ridotto, a causa della minore concentrazione di veleno nella vittima. Un umano, paradossalmente ha più opportunità di sopravvivere ad un getto di veleno diretto rispetto ad un soffio però, in quanto l'area coperta dal soffio è molto grande. Come se non bastasse, il sangue del drago è velenoso, così come la carne. La stessa tossina che produce per lo sputo, viene trasportata dal sangue.
** Rosso: I draghi rossi sono i draghi che più sono diventati parte dell'immaginario popolare e del folklore tra le varie razze senzienti. Questo perchè tra le varie specie draconiche sono i più aggressivi. Il drago rosso è simile in dimensioni ad un drago bianco, ma è più snello ed alto rispetto ad esso. Le robuste ali terminano in due piccoli artigli, che gli consentono di arrampicarsi con facilità. La pelle è spessa, e lungo la parte anteriore del collo, ed il ventre, è coperta da scaglie biancastre molto dure, mentre delle squame rosse coprono il resto del corpo. Due file di piccole scaglie ossee partono dal naso dell'animale e lo percorrono in tutta la lunghezza, unendosi in una fila all'attaccatura della coda. I draghi rossi vivono ovunque sulla terra ferma, soprattutto in luoghi ricchi di grotte e caverne. Quando attacca, o viene attaccato, il drago utilizza come arma principale il suo soffio: l'animale produce, in un organo apposito, un liquido viscoso che si infiamma a contatto con l'aria. Quando soffia, la sua trachea si riempie di questo liquido, e si mescola con l'aria espulsa dai polmoni. Questo fa si che il liquido inizi a bruciare già all'interno del drago, e ha portato alla concezione errata che il drago soffi fuoco. In realtà, quando lascia la bocca del drago, il liquido che sta bruciando si attacca alla vittima e continua a bruciare, incendiando la preda. Un soffio prolungato è in grado di fondere il ferro, anche se di rado il drago concentra il suo soffio in un'area ristretta. Oltre alla preda, il drago mira ad incendiare l'area circostante, in modo da disorientarla ed impedirne la fuga, se non attraverso altre fiamme, o verso il drago stesso.
** Verde Il drago verde, nonostante il suo aspetto, è una creatura pacifica, e mansueta. Non è raro vedere draghi verdi fungere da cavalcature, o animali da compagnia, molto intelligenti ed in grado di parlare, ma pur sempre animali. Il drago verde ha un collo ed una coda più lunghi rispetto ad un drago rosso, ma le dimensioni sono molto simili. Dalla testa del drago partono due paia di corna, che curvano verso l'alto e in avanti. Le ali del drago verde sono molto sviluppate, e nonostante le dimensioni, può avvicinarsi molto come abilità al drago azzurro. Di rado attaccano di loro iniziativa, solitamente lo fanno solo per nutrirsi, o se sono impiegati come cavalcatura in battaglia, nonostante siano dei nemici temibili e molto potenti. Il drago verde si difende in un modo simile a quello del drago nero: produce infatti una bile molto acida, che è in grado di sputare in un getto prolungato. Questa bile è in grado di sciogliere completamente un'armatura nel giro di pochi minuti, e se l'acido entra in contatto con la pelle o pelliccia, in genere causa forti bruciature da acido, e non è raro che scavi un buco nella vittima. Alternativamente la bile può essere nebulizzata, questo copre un'area molto vasta di una nebbia irritante che può causare danni che variano dalla cecità temporanea alle ustioni o morte per soffocamento. Il suo soffio però non è l'unica arma di cui dispone. Non è raro vedere un drago verde utilizzare le corna per infilzare i nemici se messo alle strette, o ricorrere al morso ed agli artigli. Vista la loro connessione con Londrun, i draghi verdi sono ritenuti sacri dagli Elfi Silvani.
** Viola: Il drago viola è indistinguibile da un drago azzurro, tranne che per il colore. Anch'esso ha le ossa cave, le ali molto sviluppate ed una placca alla fine della coda. Vengono considerati da chi va per mari, come un di cattivo auspicio, in quanto la loro presenza indica una tempesta nelle vicinanze. I draghi viola amano particolarmente le tempeste, in quanto sono spesso accompagnate da fenomeni elettrici. Il drago è in grado di immagazzinare una carica elettrica nel suo corpo, o di generarla. Lungo il dorso, dopo l'attaccatura delle ali, fino alla coda, sono presenti degli organi appositi, che permettono al drago di scaricare l'elettricità generata a volontà. Generalmente viene scaricata attraverso la placca posta sulla coda del drago, che viene impiegata come una lama. La scarica elettrica che rilascia è abbastanza potente da uccidere qualsiasi creatura più piccola, o di stordire un altro drago. Solitamente innocui nei confronti delle altre specie senzienti, tendono a vivere lungo le coste, e non è raro vederli assieme ai draghi azzurri.

* Viverne: Le viverne sono animali intelligenti in grado di parlare, di razza draconica, nate da una perversione dei draghi da parte del dio elfico NOMEDIO. La viverna ha due ali terminanti in un lungo artiglio, che vanno a sostituire le zampe anteriori, mentre le grosse zampe posteriori sorreggono tutto il corpo della creatura. La testa è simile a quella di un drago, tranne che per un becco aquilino che va a sostituire la bocca. La pelle è composta di scaglie taglienti, che vanno dal marrone scuro al grigio. Dalla testa, lungo tutta la lunghezza del corpo si sviluppano piccole creste ossee, e la coda termina in un lungo pungiglione velenoso. La viverna non è grande come gli altri draghi, gli esemplari più vecchi infatti, rimangono comunque di dimensioni inferiori ad un drago azzurro o viola. Sono feroci predatori che vivono in piccoli branchi di 5 o 6 esemplari. Attaccano qualsiasi creatura deliberatamente, e, se in branco, rappresentano un serio pericolo anche per un drago dorato o marrone. Sono in grado di comunicare tra loro, ed in genere con altre specie draconiche, ma la comunicazione è in genere molto superficiale.

* Nani: Jotraanviir, vedendo la creazione degli elfi, plasmò dalla roccia delle creature umanoidi, più basse e robuste, che più rispecchiavano la roccia da cui erano stati creati. In seguito chiese a Londrun di dare vita alle creature, il quale, divertito dall'aspetto dei primi nani, acconsentì. Nacquero così dalla roccia, e vennero subito benedetti dal signore delle montagne con una grande conoscenza dei metalli e delle pietre preziose. I nani vivono a lungo, circa 2-3 secoli. Inizialmente vivevano a Gorlanos, nella città che oggi si chiama Norlyn, ma col tempo si sono spostati prima su tutta la zona nei pressi della montagna stessa, e poi sentendo voci di grandi ricchezze ad est, alcuni gruppi si sono stabiliti a Talenalia, e Vallea. Nei confronti delle altre razze sono generalmente diffidenti. Dopo la catastrofe e la migrazione elfica, sono entrati in contatto con gli elfi: dopo qualche scaramuccia, ed un lungo processo diplomatico, i nani della montagna hanno accolto gli elfi silvani, consentendo loro di popolare la grande foresta ad ovest della montagna. Più o meno lo stesso è stato per i nani di Balir, seppur più rapidamente: gli elfi silvani vivono nella foresta a nord di Exeter, la vecchia capitale nanica. Nei confronti degli elfi alti invece c'è un rapporto di disprezzo reciproco, che ha portato ad una lunga e devastante guerra.

* Gnomi: gli gnomi sono una razza comparsa dopo la catastrofe di Krater. Sono piccole creature bipedi, che raramente superano il metro di altezza, con tratti somatici che ricordano molto gli elfi. Sebbene le loro origini siano incerte, non è da escludere che siano anch'essi una mutazione della razza elfica, dovuta alle tempeste astrali. Gli gnomi presentano una forte sintonia con il piano astrale, ed un'eccezionale intelligenza. Vivono come gli umani, circa un secolo, e non hanno formato una nazione indipendente, bensì si sono mescolati alle altre razze, inserendosi nelle società come accademici, studiosi e sapienti. Vista la loro astuzia, non è raro che vengano impiegati come consiglieri e diplomatici, soprattutto nelle nazioni umane. Un piccolo gruppo di gnomi, stabilitosi a Norlyn, si è adattato molto in fretta alla vita sottoterra, ed hanno appreso dai nani il loro amore per le pietre preziose.

* Elfi Aviani: Dopo la catastrofe che ha devastato Arhada, gli elfi sono fuggiti dal continente, migrando verso nord e nord-ovest. Non tutti però sono riusciti a fuggire, ed alcuni di loro sono stati mutati dalle tempeste astrali che spazzano l'isola. Gli elfi aviani sono una mutazione intelligente degli elfi, che attraverso secoli di evoluzione accelerata, sono diventati un ramo semi-stabile della specie elfica. Le varie mutazioni degli esseri senzienti del continente hanno portato a molti esemplari di creature mutate, ma gli aviani si sono distinti in quanto sono una delle poche mutazioni non sterili. La loro capacità di volare inoltre, ha ridotto l'esposizione alle prime e più devastanti tempeste: all'occorrenza infatti, semplicemente se ne andavano. Col tempo, e vista la longevità degli elfi, da elementi singoli si sono uniti in piccoli gruppi, che si sono insediati nelle città più esterne del continente, soprattutto a sud. Fisicamente gli aviani si dividono in 4 caste, a seconda del grado di mutazione: nome1, quelli che mantengono di più l'aspetto elfico: le ali prendono il posto delle braccia, e terminano in 3 artigli che usano come mani. I nome1 sono la casta governante, e di sacerdoti. Nome2 indica gli aviani con un grado di mutazione superiore, ma che mantengono comunque visibili tratti elfici, e l'intelligenza che avevano un tempo; anche loro hanno le ali al posto delle braccia, ma oltre a quelle, la parte inferiore delle loro gambe è simile a quella di un uccello. Un collare di piume ne adorna il collo e copre le spalle. Nella società ricoprono ruoli di istruzione e supervisione, sono quelli più dotati nell'uso della magia. La terza casta, nome3 indica gli aviani il cui corpo è completamente ricoperto di piume, conservano ancora le braccia che avevano un tempo, anche se sono alate. La parte inferiore del corpo è quella di un uccello, con le zampe che terminano in 3 artigli, ed il ginocchio invertito. Sono mediamente intelligenti, e nella società sono artigiani rispettati. Nome4 indica invece tutti gli aviani che non sono in grado di volare. Buona parte di essi è completamente ricoperta di piume, ma privi di ali. Le braccia terminano in mani artigliate, la testa è più piccola, e le gambe sono quelle di un uccello. Nella società aviana fungono da costruttori, agricoltori, servi, e fanteria.

* Vampiri: Sebbene non siano propriamente una razza a se stante, i vampiri sono più diffusi di alcune razze, ed hanno una loro nazione, la Repubblica Scarlatta. Il vampirismo si è presentato come una malattia incurabile, che, nel corso di poche settimane, causa la perdita di forze e vitalità nella vittima, fino a causarne la morte. In certi casi però, se la vittima è abbastanza forte, la malattia la fa entrare le vittime in uno stato di coma profondo simile alla morte, che può variare in durata dalle poche ore ai giorni. Se la vittima si risveglia, sente l'impulso di nutrirsi di carne, ma soprattutto di sangue. Qualora ci riesca, il corpo lentamente si ricostituisce, tornando a com'era alla contrazione della malattia. Inoltre, col tempo, il vampiro nutrendosi rinvigorisce, e le sue capacità fisiche migliorano notevolmente. La morte però sembra non sopraggiungere mai: i vampiri infatti sono immortali, anche se possono essere uccisi. Fisicamente un vampiro appena risvegliatosi dal coma, si presenta come un umanoide dal pallore mortale; è freddo al tatto, non respira ed il cuore non batte. Il corpo si presenta come quello che aveva in precedenza, tranne per il fatto che la massa muscolare è scomparsa quasi del tutto, i capelli sono diventati completamente bianchi e la pelle si è ritirata. Nutrendosi, i muscoli tornano a svilupparsi, e riacquista l'aspetto di un essere vivente normale, tranne per il pallore che rimane, così come la temperatura corporea bassa. Le unghie si fanno accuminate, somigliando quasi ad artigli, e lo stesso accade ai denti. Se possibile i vampiri vengono distrutti al più presto, in quanto un vampiro lasciato a se stesso è una minaccia per la società. Sono pochi i luoghi dove un vampiro è accolto con rispetto, in molti casi infatti, appena rende nota la sua natura, si vede contro interi regni. L'unica eccezione è la Repubblica Scarlatta, che attraverso un rigido codice sociale, e un ottimo corpo di diplomatici, intrattiene rapporti commerciali e di aiuto militare con alcuni regni confinanti.

* Mezzosangue: I mezzosangue si dividono in due tipologie principali: gli uomini-bestia, e gli incroci. I primi sono generalmente disprezzati ed odiati, mentre i secondi sono almeno tollerati, anche se in alcune culture sono emarginati.
** Uomini-bestie: Per uomo-besta si intende una mutazione semi-stabile di un essere vivente. Viene adottato il termine uomo in quanto le mutazioni delle altre razze senzienti sono meno frequenti, o generalmente più instabili e meno longeve. Un uomo bestia quindi piò essere un qualsiasi essere bipede senziente, che ha subito una mutazione, ottenendo delle parti del corpo, e/o comportamenti animali. La mutazione può avvenire a causa di effetti magici, o essere trasmessa da un genitore già mutato, e può essere temporanea, o permanente. Nel caso la mutazione sia congenita, ovvero presente dalla nascita, generalmente il piccolo viene ucciso. Se appare durante lo sviluppo, o a causa di effetti magici, il soggetto viene risparmiato, ma condurrà in genere una vita ai margini della società. In molti casi gli uomini bestia abbandonano la civiltà, e si riuniscono in piccole tribù, che possono avere anche comportamenti violenti nei confronti delle razze "pure". Non è raro che diventino razziatori e saccheggiatori. In genere le tribù mantengono numeri ridotti, in quanto la sabilità fisica e mentale dei singoli membri rende un'organizzazione complessa abbastanza improbabile.
** Incroci: un incrocio è un  figlio nato da un rapporto tra due razze senzienti. Ad eccezione dei mezzi draghi, che sono largamente accettati e stimati nella società, gli altri incroci sono tollerati, ma può capitare che vengano leggermente marginalizzati o discrimminati. Gli incroci con la specie orchesca in particolare vengono discriminati da gran parte della società.

* Demoni: Maghi più o meno potenti, che non sono stati in grado di controllare il loro potere, il quale li ha consumati. Succede solo a maghi che utilizzano le proprie emozioni per invocare la magia. Una volta consumati, cercano fonti di nutrimento attraverso le quali accrescere il loro potere. Diventano esseri di magia pura, che hanno come obiettivo consumare creature simili a loro, sia sul piano materiale che astrale. Sono in grado di spostarsi liberamente tra i due. I più deboli in genere iniziano ad accrescere il loro potere nutrendosi delle emozioni degli esseri viventi, e cercando di assorbirne lo spirito. I più potenti invece spesso attaccano Caras Astra, o qualsiasi guardiano trovino. Seppur privi di intelligenza, hanno un istindo di sporavvivenza e coscenza di se.

* Guardiani: Maghi più o meno potenti che si distaccano troppo dal piano materiale, volontariamente o meno, diventando dei gusci nei quali l'energia astrale, quindi la magia, scorre quasi liberamente. Il loro corpo viene animato da questa energia, e trattengono una minima parte della loro intelligenza. I guardiani si trovano spesso dove ci sono grandi concentrazioni di energia astrale, poiché ne sono attratti; sono molto sensibili alla magia, e la loro natura semi senziente li rende ottime guardie del corpo di maghi e viaggiatori astrali. A differenza di un demone, consumato dalle proprie emozioni, il distaccato guardiano cerca di controllare l'energia astrale che lo pervade, e di portare un equilibrio tra se stesso e ciò che lo circonda. Vede i demoni ed alcuni utilizzatori di magia come creature deplorevoli, e cercherà di distruggerle sempre, per restituire l'energia astrale che hanno rubato. 