= Sulle divinità

Le divinità sono aspetti del piano astrale in grado di intercedere nel piano materiale. Sono connessi a quest'ultimo in quanto il numero di creature che credono nella loro esistenza, e che li adorano influisce direttamente sul loro potere. Le varie specie inoltre adorano aspetti diversi delle stesse divinità. I 9 draghi immortali

I draghi, i lucertoloidi ed i coboldi adorano quelli che loro chiamano 9 grandi dragoni, ovvero divinità basate sugli elementi, e sui colori dei draghi stessi. Queste divinità sono:

* Aazrelag, il grande dragone rosso, dio del fuoco, signore dei vulcani
* Avyumakra, il grande dragone bianco, dio del ghiaccio, signore dell'inverno e dei ghiacci
* Drogshul, il grande dragone dorato, dio del potere astrale, signore della magia
* Jotraanviir, il grande dragone marrone, dio della terra, signore delle montagne
* Kaalvurn, il grande dragone nero, dio della morte, signore dei morti
* Levhithkron, il grande dragone blu, dio dell'acqua, signore dei mari
* Londrun, il grande dragone verde, dio della vita, signore di tutte le creature viventi
* Nehrothkras, il grande dragone azzurro, dio dell'aria, signore dei cieli
* Rolaan, il grande dragone viola, dio del fulmine, signore delle tempeste

Gli elfi silvani hanno un pantheon diverso, adorano i vecchi dei elfici:

* Londuril, il primo tra gli dei, signore della vita e delle foreste
* Kalantis, il dio elfico del sole, del fuoco e della guerra
* Sillamen, dio della caccia ed in seguito della morte
* Melios, signore dei ghiacci e delle montagne
* Lameril, signore dei mari e della pioggia

Gli elfi alti rifiutano l'esistenza di  divinità, nonostante abbiano avuto una prova diretta della loro esistenza. Riconoscono l'entità che li ha creati, e le entità che li hanno manipolati come esseri molto potenti, ma alterabili e mortali. Inizialmente aderivano anch'essi allo stesso pantheon adorato dagli elfi silvani. Ma con l'avanzamento tecnologico della loro razza, hanno abbandonato la religione preferendo perdersi nella loro vanità e grandezza.

I nani, pur riconoscendo l'esistenza di altre entità divine, adorano Jandvaark, il loro padre creatore, che li ha plasmati dalla roccia, signore delle montagne e dei metalli, ed Aazelra, la dea dei vulcani e del fuoco, signora della forgia. Hanno inoltre una terza divinità: Muzar, divinità della guerra e dei guerrieri.

Gli gnomi sono creature poco religiose, e sono privi di un loro pantheon, generalmente si affidano alle religioni dei luoghi dove vivono, ma non è rado trovare gnomi, soprattutto maghi, che non vedono le varie divinità come tali, ma piuttosto come entità del piano astrale molto potenti.

Gli umani hanno diversi pantheon a seconda del luogo.

Gorlanos: Nel continente di Gorlanos, gli umani hanno inizialmente adottato una religione politeista, che ha visto il numero di divinità ridursi fino ad arrivare a 5 divinità principali: 
* la Madre
* il Vecchio
* l'Amante
* l'Operaio
* il Soldato

Queste 5 divinità rappresentano per gli umani di Gorlanos i 5 elementi che governano la vita di ogni uomo: la Madre rappresenta la nascita, la vita e la famiglia; il Vecchio rappresenta la conoscenza, la magia e la morte, l'Amante rappresenta l'amore, la felicità ed il piacere, l'Operaio rappresenta il lavoro, la fatica e le arti ed il Soldato rappresenta la fedeltà al proprio signore, la guerra e la disciplina.

Adahimia: Nel continente di Vallea ci sono diversi culti, ma quello principale è costituito da un unico dio, chiamato Vernal, e del suo prescelto, l'Imperatore visto come un semidio. 

Elelia: Nell'isola di Elelia, il culto principale è quello di Vernal, ma non riconoscono l'imperatore di Adahimia come autorità divina.

Ignariti: la religione degli ignariti, a causa delle loro razzie ha preso molto dalle religioni delle altre popolazioni: la popolazione ha un pantheon composto da due divinità principali che si scontrano in un'eterna lotta: la dea Sigrana, il cui culto prende dalla Madre, Vernal e Londrun, e dall'altra parte Tormigron, signore della morte e del ghiaccio. 

Un caso particolare sono gli orchi: un detto comune in Adahimia recita: "ogni orco ha due divinità: se stesso ed il suo capo". Gli orchi infatti non hanno mai considerato l'idea di entità divine, e nella società orchesca dove i più deboli vengono oppressi, ogni membro si considera al di sopra di quelli più deboili di lui, mentre cercherà sempre di guadagnarsi la "benevolenza" del proprio capo, ovvero farà di tutto per non farsi uccidere dal suo superiore. Gli ogre invece sono semplicemente troppo stupidi per avere un lato "spirituale". I goblin invece adorano quello che loro chiamano il Goblin Nero, un dio non propriamente malvagio, ma che promuove l'insurrezione dei goblin contro i loro padroni orcheschi. Questo culto ovviamente non è ben visto dagli orchi, che cercano di estinguerlo.