= Sulle fazioni

== La nobiltà nel mondo:

Le varie fazioni del mondo hanno sviluppato una loro cultura, e dei sistemi di nobiltà diversi.

=== Gorlanos

La nobiltà nel continente di Gorlanos è la classe dominante, ed i titoli sono ereditari. Nella Repubblica Scarlatta e nella Gilda della Fenice i titoli nobiliari con il passare dei secoli sono caduti in disuso, mentre negli altri regni del continente è ancora la classe dominante, anche se i nomi hanno subito variazioni.

Impero di Meridia:: 
Imperatore
Duca
Barone
Principe
Cavaliere

Regno Del Sottosuolo::
Re della Montagna
Principe
Reggente
Mastro

Ducato Vulic::
Gran Duca
Conte
Barone
Signore

Principato di Carenia::
Principe Reggente
Conte
Signore

=== Shorlea

Nel continente di Shorlea la nobiltà svolge ancora un ruolo primario nel governare la società, ad eccezione dei popoli barbarici noti come Ignariti, per i quali il grado di nobiltà è insignificante.

Figlie di Talena::
Madre suprema
Matriarca
Padrona

Regno di Balir::
Re della Montagna
Gran Principe
Governatore
Sovrintendente

Legione di Tilgan::
Comandante Supremo / Gran Ammiraglio
Generale / Ammiraglio
Governatore
Capitano del Popolo

=== Vallea

In Vallea,come nel continente di Shorlea, la nobiltà è al centro della vita politica

== Arhada

L'isola di Ar-hadda, oggi nota semplicemente come i Pilastri, è stato il primo continente abitato da specie senzienti. Esso infatti è dove sono stati creati gli elfi, e la storia del continente è per certi versi la storia degli elfi. Inizialmente il continente era un'unica isola, che si univa al mare con dolci spiagge, e rilievi generalmente bassi. Col tempo gli elfi hanno iniziato a padroneggiare la magia, e col passare dei millenni, anche la loro tecnologia è avanzata. Questo ha permesso loro di plasmare il continente a loro piacimento. Per meglio proteggersi dalle incursioni dei primi proto-orchi, hanno iniziato rialzando la parte settentrionale dell'isola dal mare, tramite una combinazione di magia e tecnologia. Questo cambiamento ha alterato l'ambiente circostante, e, gli dei che vedevano questo come un affronto al loro creato hanno ammonito gli elfi. Questo avvertimento ha temporaneamente arrestato il loro sviluppo tecnologico, ma non li ha fermati dall'organizzare incursioni nei continenti circostanti al fine di catturare orchi ed utilizzarli come schiavi. L'influsso di nuova manodopera ha reso possibile la costruzione di meraviglie archittettoniche, e ha consentito agli elfi di concentrarsi di più sullo sviluppo tecnologico, incentivato anche dalla guerra in corso con gli umani di Vallea. Questa guerra però si è conclusa con la quasi completa distruzione della popolazione elfica: 

== Gorlanos

Il continente di Gorlanos è stato il primo continente in cui si è sviluppata una civiltà umana ed una nanica. I primi nani infatti vennero animati nel Monte Cavo, che i nani chiamano Aar-Mosser, Montagna del Dio. 

=== Impero di Meridia

Teria, Kheria, Carenia, Thudora, Wrokia e Turraia

L'isola di Meridia, la più grande del continente di Gorlanos, era tutta sotto il controllo dell'Impero locale, chiamato appunto Impero Meridiano, o Impero Teriense. Le origini dell'impero sono da tracciare a 5 secoli prima della catastrofe; i primi insediamenti umani si sono espansi, fino a formare dei piccoli regni in contrasto tra loro. Per circa 350 anni questi staterelli si sono combattuti, e nel 2409CD, in quello che poi è diventato nel calendario imperiale l'anno 0 di Meridia, o Anno Meridiano, il regno di Teria, con capitale a Laria ha stretto un'alleanza con i regni orientali di Kantes e Ghellia e Kheria, formando un proto-impero, di cui si è nominata sovrana. Durante il suo regno, l'Imperatrice di Meridia si è impegnata ad unificare sotto la sua bandiera tutti i piccoli regni in cui era suddivisa l'isola, compito che però ha portato a termine il secondo imperatore di Meridia, suo figlio, nel 44AM (2453CD) L'impero in seguito alla sua unificazione è stato suddiviso in 7 province: Teria, con capitale Laria, Wrokia, con capitale Norlyn, Ghellia con capitale Lindos, Kantes con capitale Carelian, Kheria con capitale Medor, Turraia con capitale Ederla e Thudora con capitale Tedara. 

Le 6 province riconoscevano l'autorità del sovrano di Teria come Imperatore, ed erano legate da un accordo di sostegno comune, sia militare che commerciale, anche se non avevano molti rivali attorno, ad eccezione delle tribù orchesche che di tanto in tanto invadevano la parte meridionale dell'isola. Inizialmente l'impero era molto stabile, ed ha prosperato, con la fondazione di accademie navali e militari, che promuovevano l'avanzamento tecnologico. Nel 72AM(2481CD), una disputa sulla successione vede le due province di Ghellia e Kheria scontrarsi. Alla guerra si aggiunge Turraia, schierata dalla parte di Ghellia. La guerra dura diversi anni, e nel 75AM(2484CD) intervengono anche le forze imperiali a cercare di ristabilire l'ordine. Temendo di perdere territori, Il duca di Ederla e governatore di Turraia ritira il proprio esercito, mentre la città di Lindos viene assediata. Nel 79AM(2788CD) la città si arrende, ed il governatore di Ghellia, come punizione per l'aggressione ad una provincia imperiale viene destituito. Parte dei territori di Ghellia vengnono annessi alla provincia di Kheria, che controlla tutte le isole orientali del continente. Il territorio compreso tra Kentos ed il mare viene assegnato al duca di Carelian, e la provincia viene rinominata in Carenia. 

Durante il periodo della guerra, alcune navi, provenienti principalmente da Turraia approdano sull'isola di Vagra, dove sono stati stabiliti piccoli insediamenti, quasi esclusivamente sulla costa. Per i 20 anni successivi gli insediamenti sono cresciuti, ed esploratori si sono portati fino al confine opposto dell'isola, grazie ad una serie di campagne militari atte a ridurre la popolazione orchesca. Nel 93AM(2802CD) le colonie sull'isoa di Vagra, da territori della provincia di Turraia, sono diventati una provincia imperiale indipendente, che ha preso il nome dall'isola, e con capitale Sernost, ed il governatore della città venne nominato Barone. Allo scoppiare dell'epidemia di vampirismo tra il 150-151AM (2859-2860CD), la nuova provincia imperiale di Vagra è stata devastata. L'epidemia è stata interpretata come una punizione divina, ed ha marchiato l'isola come maledetta. La popolazione che è riuscita, è fuggita dall'isola, mentre il resto è stato confinato nell'isola. I malati dell'isola di meridia sono stati banditi sull'isola di Vagra, ed è iniziato un periodo di psicosi generale che ha portato all'uccisione o deportazione dei malati. L'impero però non era disposto a lasciar andare così facilmente la nuova provincia, e, dopo il caos iniziale causato dall'epidemia, sono state organizzate campagne di propaganda per ripopolare l'isola, supportate da una presenza armata consistente. La presenza di sopravvissuti all'epidemia, non ha permesso alla nazione di mantenere le colonie. Successivamente all'isolamento dell'isola infatti, una delegazione di sopravvissuti è giunta nella città di Laria, con l'intenzione di avvicinare la giovane provincia all'impero. Una volta chiarita la loro provenienza, però, i delegati sono stati uccisi e bruciati, per paura che potessero causare una nuova epidemia. Per lo stesso motivo, è stata organizzata rapidamente una spedizione militare nell'isola, mirata a rimuovere cause di un possibile contagio. Successivamente a questa spedizione, vi è stato un breve periodo in cui l'impero stesso ha finanziato il ripopolamento dell'isola, a partire dalla città di Sernost. Questa nuova spinta coloniale però ha iniziato a subire dei rallentamenti.

A causa dell'epidemia, e delle incursioni dei sopravvissuti nei territori rurali delle nuove colonie imperiali, l'isola si è guadagnata la fama di essere maledetta. Per contrastare questi timori, nell'anno 2873 è partita una grossa spedizione militare volta a rendere le colonie sicure. Sono state erette nuove fortificazioni lungo le strade principali, e nelle città; è stato inoltre organizzato un gruppo militare delle colonie, e nel secolo successivo, la parte settentrionale dell'isola di Vagra è stata riconosciuta come provincia imperiale a tutti gli effetti. Durante i successivi 4 secoli, la provincia si è espansa, seppur lentamente, soprattutto a causa delle incursioni di orchi e mutanti da sud, ed è arrivata ad occupare tutto il territorio costiero della parte settentrionale dell'isola. In questo periodo di pace, l'Impero ha prosperato, e sono state organizzate spedizioni ad est ed a sud, al fine di scoprire nuovi territori da colonizzare. Questo ha portato alla scoperta della fonte di tutte le incursioni dei mutanti del sud.

=== Città Stato di Tedara

La città stato di Tedara era, ai tempi dell'Impero, il principale centro di addestramento e alloggio delle truppe imperiali. Dopo la fondazione di Staria ed il completamento della Torre delle Catene, l'imponente torre-prigione a nord ovest dell'isola, la sua importanza è notevolmente aumentata. L'effettiva separazione della città ed i																							
territori ad essa legati, risalgono a circa 350 anni addietro, quando, alla morte dell'Imperatore di Laria, vi erano 3 pretendenti al trono: il primo duca Vulic, il barone Vorth, e l'erede dell'Imperatore. La supremazia di quest'ultimo sugli altri fu dovuta ad una promessa di terre fatta al primo duca e a Vorth. che ricevettero																							
rispettivamente la città di Ederla e Staria. In seguito, Vorth, grazie alla sua magia, riuscì a contattare un'entità degli inferi che gli concesse l'immortalità. Grazie a questo dono, ed il suo controllo su demoni e diavoli, oganizzò un'evasione di massa dalla Torre delle catene, grazie alla quale riuscì a prendere il controllo su																							
Tedara, proclamandosi dittatore. Inizialmente la popolazione sottostava alla dittatura, più per paura che per volontà propria. Ribelli e dissidenti infatti, venivano deportati alla Torre, dove si dice venissero torturati. Col tempo però il Dittatore stesso, capì la pericolosità di ciò, e da circa due secoli ha avviato una modernizzazione																							
ed una guida "illuminata" del suo regno, pur intrattenendo molti rapporti con gli esterni malvagi su cui aveva fatto affidamento per reclamare il trono. Ora il popolo lo vede come un potente guardiano e protettore della loro libertà, e grande innovatore, accettando di buon grado il suo comando, nonostante non tutti siano 																							
favorevoli alla presenza degli esterni nelle loro città, pur considerandoli un male necessario alla difesa delle loro case. La città stato è tuttora in guerra con l'Impero di Meridia, mentre si mantiene abbastanza neutrale con gli altri regni.

=== Ducato Vulic

Il Ducato Vulic è nato in seguito ad una disputa sulla successione al trono Imperiale circa 350 anni fa, conclusasi con la promessa di terre ai due contendenti da parte del legittimo erede al trono. Inizialmente il Ducato comprendeva solo la città di Ederla e qualche villaggio ad essa legato. Successivamente, durante le 																							
epidemie che devastarono Meridia, la città divenne un importante scalo per il trasporto dei malati verso l'isola di Vagra. In seguito alle epidemie, il DUcato ha esteso la sua influenza alle città di Azug ed Icta, che sono passate sotto il diretto controllo di Ederla. Qualche anno dopo la secessione di Norlyn e delle isole del Mar d'Oro,																							
Il DUcato approffitto ulteriormente della debolezza dell'Impero per appropriarsi della città di Sindan. L'Impero, vista la rapida espansione del Ducato, e conscio della sua debolezza, stipulò un accordo di non belligeranza. L'ultimo duca mortale, è spirato circa 80 prima degli avvenimenti attuali, ed il trono è passato alla 																							

=== Gilda della Fenice



=== Principato di Carenia

Le terre dei ribelli di Meridia, si estendono da costa a costa nel lato orientale dell'isola. La ribellione è l'epilogo di un malcontento serbato nei secoli verso l'imperatore. L'esilio dei malati durante le epidemie e la secessione dei vari regni dall'impero, non hanno fatto che aumentare questo malcontento, ed a dare l'idea che la tirannia																							
di Laria stesse per finire. Circa un secolo prima degli avvenimenti attuali, il comandante delle truppe a Carelian ha dato il via alla ribellione, uccidendo il governatore della città, e vari funzionari imperiali. Da allora, sfruttando i fiumi e la Barriera Verde, i comandanti della città mantengono il controllo su un'area relativamente vasta																							
dell'isola. Attualmente è controllata da un comandante militare, che funge anche da governatore, eletto dal popolo ogni 5 anni.																							

=== Regno Libero del Sottosuolo

Il Regno Libero del Sottosuolo era originariamente parte dell'Impero di Meridia, separatosi durante le epidemie che devastarono l'isola. Nella città di Norlyn, scavata sotto la montagna più alta dell'isola di Meridia, il regno ha iniziato a prosperare, soprattutto grazie all'ingegno ed industriosità della sua gente. La ricchezza di questo popolo, infatti è derivata dalla vendita dei loro prodotti ad alta tecnologia, come navi a vapore e costrutti. Gli stessi costrutti e navi, costituiscono gran parte della loro potenza bellica. Col passare del tempo, da una nazione di quasi esclusivamente gnomi e nani, il regno è diventato un miscuglio eterogeneo di tutte le razze del sottosuolo, e qualche umano occasionale. Il regno è sempre stato governato da un Concilio dei rappresentanti delle varie razze. Attualmente vi sono 3 rappresentanti per le razze principali (drow, nani, gnomi) e un rappresentante per le varie minoranze	(principalmente umani)	

=== Repubblica Scarlatta

L'isola di Vagra, essendo la parte più a sud del continente, è stata la prima ad essere colonizzata dai popoli provenienti da Ar-hadda. All'epoca della catstrofe, la popolazione era costituita principalmente da elfi silvani ed i loro schiavi umani, insediatisi soprattutto nella parte settentrionale dell'isola, a causa delle frequenti incursioni di orchi e aviani, provenienti da Arhada e Valentar, e faceva parte dell'Impero di Meridia. Alla comparsa dell'epidemia di vampirismo, iniziata proprio sull'isola, probabilmente a causa di uomnini besta provenienti da sud, quasi tutta la popolazione è stata decimata. L'intera isola è stata messa in quarantena inizialmente, e con il passare delle settimane, e col diffondersi della malattia anche nelle coste settentrionali di Meridia, tutti i collegamenti con l'isola sono stati completamente tagliati. Dopo alcune settimane, un gruppo di esponenti della nobiltà imperiale, sopravvissuti e trasformatisi in vampiri, hanno cercato di ristabilire l'ordine nell'isola, radunando le poche centinaia di persone immuni o mutate, ed hanno iniziato a ricostruire la città di Sernost, sulla costa nord-occidentale dell'isola, e di ristabilire i contatti con l'Impero. La delegazione inviata a Laria però, non ha fatto ritorno; al suo posto è arrivata una flotta imperiale che ha iniziato a bombardare la città, e a far sbarcare un esercito che l'ha occupata. La popolazione, ed il consiglio di nobili che governavano la città è fuggita ad est, rifugiandosi ai piedi di un altopiano, dove ora si trova la città di Ethedan.

I sopravvissuti hanno condotto una vita frugale, nascondendosi nelle caverne, per evitare le pattuglie dell'esercito che li stavano cercando. Intanto l'impero aveva difficoltà a mantenere l'insediamento di Sernost, e la ripopolazione delle altre città abbandonate, questo perché l'isola era vista dalla gente come un luogo maledetto, ed erano pochi i coloni disposti ad insediarvisi. Intanto la popolazione di Ethedan creasceva, lentamente, anche grazie alle incursioni nelle colonie imperiali per diffondere il vampirismo. Le sparizioni di coloni hanno ulteriormente contribuito alla cattiva reputazione dell'isola, e lentamente le popolazioni delle varie città sono state spostate a Sernost. Le attenzioni imperiali all'isola sono andate scemando, a causa dei costi per mantenere le colonie, ed alla mancanza di coloni volontari. Ethedan invece continuava a crescere, soprattutto grazie all'immortalità di buona parte dei suoi abitanti. Nonostante la loro natura, i vampiri di Ethedan, visto il numero esiguo della popolazione rimasta umana, si sono imposti di nutrirsi solo di animali, e di proteggere i compagni umani. Questa convivenza pacifica tra le due razze ormai distinte, ed il nemico comune, ha contribuito all'unità della città. 

Per circa 4 secoli quella che era a tutti gli effetti una città stato ha prosperato, espandendosi nella zona circostante, soprattutto verso sud, respingendo gli invasori mutati. Un'intensificazione delle tempeste astrali ha portato ad una nuova epidemia, più violenta che si è diffusa anche a nord, oltre il mare, e scatenando disordini in tutti i territori dell'Impero. Gli abitanti di Vagra ne hanno approfittato per scacciare le forze imperiali, notevolmente ridotte in numero e prendere definitvamente il controllo di Vagra. Con la presa di Sernost, si sono proclamati una nazione indipendente, togliendo l'isola al controllo imperiale. Successivamente alla proclamazione, sono stati inviati emissari in tutte le capitali provinciali di Meridia, chiedendo di essere riconosciuti come nazione indipendente. Dei 13 nobili costituenti, in 4 ne hanno riconosciuto l'indipendenza, in cambio di un supporto militare e diplomatico in caso di necessità. Questi 4 nobili erano i capi di casati molto influenti nell'impero: la famiglia Sundvik, il cui capostipite era governatore di Norlyn e primo membro del consiglio della provincia, che temevano un'attacco da Tedara, e aspiravano all'indipendenza, la famiglia dei duchi Vulic, che controllavano il territorio più vicino all'isola di Vagra, i quali temevano un eventuale invasione, il capostipite della famiglia Silrey, principe di Carenia, il quale cercava appoggi per ascendere al trono, ed il governatore di Medor, Kaalios Gaunn, attirato dalle possibilità ad aprire i commerci ed espandere la propria influenza a sud. 

Con l'indipendenza, la neonata Repubblica Scarlatta ebbe un periodo di relativa stabilità, durante il quale venne regolamentato il governo della nazione: ogni 6 anni, tutti i cittadini umani e non, di una certa ricchezza, dovevano eleggere un consiglio composto da 3 rappresentanti umani e 3 rappresentanti vampiri. Inoltre ogni governatore delle città doveva nominare un umano ed un vampiro che rappresentassero la loro regione al senato di Ethedan. Il consiglio ed il senato poi nominavano un cancelliere che presiedeva entrambi gli organi. Oltre all'organizzazione politica, è stata formalizzata la creazione e l'organizzazione di un esercito, e di una marina militare.

== Shorlea

=== Figlie di Talena

Figlie di Talena													
La fiducia nel progresso tramite lo sviluppo delle arti magiche e non, è stata l'inziale idea che ha portato Talena, antica arcimaga, a creare la propria fazione. Stabilita nella parte più ad est di Talenalia, questa società matriarcale capitanata da una regina è specializzata nell'approfondire le conoscenze delle arti magiche e trarne beneficio. Se inizialmente l'intento di Talena era di progredire senza aiuti da altri regni o entità, una sua discendente molte generazioni dopo ha "ceduto" ed eventualmente ha fatto ricorso a patti e accordi con esterni principalmente malvagi, perché il loro potere potesse accrescere. La popolazione nonostante tutto non risente troppo di questi infausti accordi e a meno di non essere altolocati ed avere contatti con la cerchia di nobiltà che ha a che fare con la famiglia reale, la malvagità che permea questo governo non è dannosa, e anzi la vita è relativamente piacevole e pacifica. La magia è diffusa e spesso intrinseca in molti oggetti di uso comune, in un modo analogo a come la tecnologia del regno di Balir ha portato benefici in ogni casa, ma questo non impedisce che essa sia tenuta sotto controllo dal regno.

=== Ignariti

Coloro che credevano nella forza fisica, cercavano un luogo che creasse degli individui forti e robusti, temprati dalla spietatezza della natura incontrastata. Esiste un monte nell'estremo occidente di Talenalia che è in un perenne clima invernale feroce, in particolare quando Mastralis è in inverno: quale migliore luogo per temprare i corpi e selezionare gli individui più resistenti? Questo è il credo di Ignar, il fondatore di questo regno volontariamente posto forse nel luogo peggiore del piano. A cavallo fra Talenalia e l'isola di Marelia collegate dal mare ghiacciato, questo regno è demograficamente parlando molto piccolo. Sono poche le persone che sopravvivono. Questa selezione naturale però produce quelli che sono i migliori combattenti, robusti e stoici, le cui gesta vengono narrate in lungo e in largo e addirittura temute dallo stesso impero. Se gli altri regni hanno eserciti che contano sul numero dei propri soldati, qui si corona il detto "pochi ma buoni", un piccolo gruppo di questi uomini può fare la differenza.	
Il freddo è la loro maledizione ma anche il loro miglior alleato: rende quasi impossibile lo sviluppo di tecnologia, la coltivazione, riduce l'allevamento a quei pochi animali adatti a tale clima, e costringe questi popoli ad essere briganti e vivere di razzie alle spese delle nazioni limitrofe che li sopportano a malapena e non indicono guerra per non sbilanciare quello che da tempo immemore è noto come l'equilibrio di Talenalia: la paura di diventare nazioni indebolite dalla guerra, facili prede per il potente impero Adahim. 

=== Regno di Balir

Il regno di Balir è l'unione di coloro che credeva nel potere dello sviluppo tecnologico, e decisero di renderlo il fulcro della loro nazione.													
Proprio per questo si può dire che questo sia un regno molto diverso da tutti gli altri. I visitatori raccontano di aver visto meraviglie dell'ingegno che 													
farebbero impallidire chiunque.													
La tecnologia ha cercato di infondersi in tutti gli aspetti della vita di tutti i giorni e non solo nel lato della potenza militare.													
Balir la capitale, che da il nome al regno, è infatti un gioiello del progresso da loro raggiunto: al suo interno vi sono veicoli a vapore pubblici e personali, 													
industrie  automatizzate, rete fognaria, acquedotto a pressione e acqua calda in moltissime case.													
Sempre loro opera è stata anche la rete ferroviaria che arriva anche a collegare le varie città del regno, e anche alcuni dei regni confinanti che gli hanno													
concesso la costruzione per il bene del commercio.	

=== Legione di Tilgan

Tilgan, ex-generale agli ordini diretti dello stesso Adahim, rifiutò di prestare servizio presso i discendenti del suo defunto imperatore: anche lui come molta della popolazione, lo vedeva come essere immortale e prese la sua morte come se quell'entità fin'ora avesse preso in giro non solo lui ma tutto il popolo.
Divenne non solo disertore ma fù il primo capo della ribellione. Molti dei suoi subordinati che vedevano in lui un uomo giusto, oltre che un generale, decisero di seguirlo, come anche fece una buona fetta di popolo. Era alla stregua di una guerra civile alla fine, e Tilgan prendendo l'esempio dai draghi, capì che la scelta migliore era quella dell'esilio, già ordinato ufficialmente dal nuovo imperatore.
Uomo tutto d'un pezzo, ma di estrazione militare, la sua mentalità era marziale e non troppo flessibile: fra le varie proposte di come avrebbero dovuto	crescere come popolo, Tilgan non era dell'intento di cambiare il loro modo di vivere. Se gli altri decisero di andarsene per seguire le loro ideologie, Tilgan da conservatore decise di gestire il popolo che lo aveva seguito così come avrebbe gestito un esercito nella sua terra natia.
Nacque così la sua Legione, una nazione militare stabilitasi nell'isola più vicina al vecchio impero che li aveva esiliati, erta come a bastione difensivo nel caso che l'impero decidesse di schiacciare coloro che avevano scelto di non seguirli.	

== Valentar

L'isola di Valentar non ospita una nazione vera e propria, ma solo due piccole città: Vhir e Londaure. Oltre a questi due insediamenti però, al centro dei monti Tresmion, 

=== Vhir

L'isola di Valentar non è propriamente un regno come i vari regni delle altre terre, si tratta più che altro di un'isola che ospita il volontario esilio di quasi tutti i draghi che abitavano il piano. Il celestiale Adahim dominava su di loro: questo dominio era possibile grazie a potenti magie infuse in alcuni artefatti da lui creati. I draghi soggiogati in una sorta di torpore non opposero resistenza, e si lasciarono ad ogni																					
forma di sfruttamento da parte dell'impero e tutti i suoi appartenenti, popolazione inclusa: cavalcature da guerra, bestie da soma o anche cavie per esperimenti. Tutto fino a quando il celestiale morì.																					
Alla sua morte, sebbene un discedente esistesse già per ereditare da lui il controllo di Arquel, del regno e dei draghi, per qualche ragione il dominio artificiale sulla volontà dei draghi svanì permettendo ad essi di accorgersi di quello che veniva loro imposto e dando inizio alla loro ribellione: 																					
per qualche giorno i draghi più violenti e rancorosi cominciarono a seminare distruzione nell'impero, che di certo non si aspettava l'improvvisa ribellione della sua più preziosa risorsa di quel momento, e subirono grandissime perdite.																					
I draghi decisero quindi di andare a vivere in esilio in una nuova terra che avrebbero tenuto per se giurando che mai più nessun regno li avrebbe domati così com'era successo, così portando con sè vari artefatti di grande potere e anche un piccolo gruppo di persone che aveva																					
dimostrato di non volere i draghi come servi. Attraversarono il grande mare e trovarono l'isola di Valentar, reputandola adatta al loro scopo vi si insediarono fondando la città libera di Vihr abitata da draghi e da quei pochi che li avevano seguiti volontariamente.																					

Nello scorrere dei millenni l'isola non è cambiata molto. Qualunque tentativo di assalto è stato prontamente represso dalla grande potenza dei draghi, che accettano solo il passaggio di viandanti o di nuovi pellegrini che decidono di stabilirsi in quell'isola. In particolare molti disertori spesso cercano nell'isola un luogo al sicuro da qualsiasi esercito possa volere di tornare a prenderli, tuttavia non tutti sono reputati degni di soggiornare dagli stessi draghi che vedono in cattiva luce quelli che anche in passato abbiano fatto parte di una forza armata, a causa del dubbio che non siano spie o infiltrati.																					

=== Londaure 

== Vallea

=== Adahimia

Impero di Adahim																				
L'impero Adahim nasce come la iniziale casa del celestiale che ha creato il piano d'esistenza, e da lui ne prende il nome. La sua idea era quella di creare uno spazio tutto per se dove poter regnare come l'unico essere divino per il tempo rimanente della sua vita: pertanto forma i vari continenti e ne prende uno come dimora per se e il suo popolo. La creazione del piano è datata a circa 5000 anni prima delle vicende attuali, e lui ci visse per circa 300 anni, durante i quali non successe nulla di particolarmente eclatante. I popoli da lui creati o portati hanno vissuto in tranquillità, ma alcuni in paura della sua forza. Oltre ad essere lui stesso un celestiale di grande potenza, aveva creato per il suo impero una serie di elementi che sugellavano il suo dominio: disponeva di molti artefatti dal potere enorme, che gli davano il controllo dei draghi Alla sua morte, molte vicende si susseguirono: i draghi si ribellano e l'ibrido instabile torna nelle forme originali delle progenie da cui era stato creato. Come atto finale della loro ribellione oltre ai danni causati dalla loro ira, vi è la loro secessione ed esilio nell'isola vi Valentar, nella quale hanno portato gli artefatti che permettevano a Adahim di controllarli e alcuni degli umani che si erano presi cura di loro. La successione al trono andò a suo figlio, primo imperatore Aasimar nato dall'unione del celestiale con un'umana: ereditò il pieno controllo sulla totalità dell'impero e sull'isola volante di Arquel. A differenza del padre, che incorporava tutte le virtù dei celestiali, lui era imperfetto e non riuscì a mantenere lo stesso controllo che esercitava il padre. In particolare la morte di una quasi dinività causò lo scetticismo generale di chi vedeva nel celestiale un tiranno o un'entità divina eterna da venerare. Tutti coloro che per questi motivi cominciarono a lamentarsi e/o rivoltarsi vennero soppressi inizialmente e esiliati i rimanenti. Da allora l'impero ha dovuto gestire la mancanza dei draghi, che erano una forza non solo militare, ma permetteva loro di dominare i cieli anche come trasporto civile e mercantile. Si adattarono ad utilizzare molti animali e bestie volanti, che tengono sotto scacco i cieli da qualsiasi attacco proveniente dall'alto e dal basso.	Proprio per questo sono state fondate le città sulle vette delle montagne più alte, che oltre ad essere punto di sosta per i viaggi, fungono anche da strutture di addestramento degli avieri e delle bestie usate per il volo.	Nell'impero per questo il volo è abbastanza comune, nonché si tratta di un grande vanto rispetto agli altri regni. Le città principali dell'impero si trovano nelle grandi vallate racchiuse dall'enorme catena montuosa dalla Fauce: molte città sono fiancheggiate da una o più fortezze di solito posizionate lungo la costa pronte a respingere attacchi provenienti dal mare. All'interno di queste città la vita si svolge normalmente, e nonostante sia un impero la popolazione risulta relativamente contenta e vive bene. Arquel:	In tutto il piano non esiste un qualcosa di più imponente di Arquel, l'isola volante. Casa della famiglia imperiale, ereditata da Adahim in persona che l'aveva creata per essere la sua dimora, ospita anche molti nobili e ricchi che possono permettersi un posto di spicco, letteralmente. Si tratta di un'enorme massa di terra e roccia pianeggiante che levita ad un'altezza di circa 4000 metri: si dice che sia tenuta in volo da un'artefatto incastonato al suo interno, e che risponde solo al primogenito discendente diretto della famiglia imperiale.Il clima è costantemente tenuto sotto controllo dallo stesso artefatto, che permette di vivere in un'eterna primavera, nonostante l'alta quota a cui si trova. La città di Arquel è sede del castello imperiale, e di una lussuosa e grandiosa città. L'isola è protetta in molti modi, tanto da essere considerata una fortezza a tutti gli effetti. Prima protezione è data semplicemente dall'altezza e la difficoltà di raggiungerla. Tutti i mezzi aerei sono tenuti sotto controllo dall'eccezionale forza aerea dell'impero, e per chi non vola, nel mare sottostante vi sono delle fortezze-stazioni dotate di ascensori che sollevano visitatori e merci. Sull'isola sono presenti forze armate e magiche d'elite: solo i migliori possono avere il privilegio di difendere il cuore dell'impero da minaccie esterne, ed essere ricompensati di conseguenza. Infine sono presenti molte strutture che all'apparenza sono dei mulini a vento, ma che in realtà si tratta di torri di difesa: ospitano armi d'assedio e fungono da generatori eolici che permettono il funzionamento dell'attrezzatura meccanica della città, fra cui gli ascensori.

== Cronologia

[cols="3", options="header"]
|===
^.^|Data 			^.^|Fazioni coinvolte	^.^|Avvenimenti
^.^|0				^.^|Tutto il piano		^.^|Creazione dell'intero piano d'esistenza. L'anno 0 è un anno estivo.
^.^|304 / -4741 	^.^|Impero Adahim		^.^|Morte di Adahim. Inizio della stirpe reale aasimar, rivolta ed esilio dei draghi
^.^|305 / -4740		^.^|Esilio dei Draghi	^.^|Insediamento dei draghi nell'isola di Valentar, fondazione di Vihr
^.^|2348			^.^|Teria				^.^|Fondazione di Teria
^.^|2709			^.^|Meridia				^.^|Fondazione dell'impero
^.^|2859 / -3186	^.^|Arhada				^.^|Catastrofe
^.^|4486 / -559		^.^|TLDNO				^.^|Colonizzazione delle prime isole del Mar d'Oro
^.^|4492 / -553		^.^|TLDNO				^.^|Fondazione di Laria. Il primo Imperatore di Meridia sale al trono
^.^|4495 / -550		^.^|TLDNO				^.^|Fondazione di Norlyn. Colonizzazione di Asteda. Le colonie abbandonate nel Mar d'Oro vengono ripopolate
^.^|4509 / -536		^.^|TLDNO				^.^|La Torre delle Catene è ultimata. Cresce l'importanza militare di Tedara
^.^|4531 / -514		^.^|TLDNO				^.^|Viene fondata la "Gilda dei mercanti del Mar d'Oro" a Medor. 
^.^|4540 / -505		^.^|TLDNO				^.^|Le voci della prosperità dell'Impero di Meridia portano nuovi coloni dalle terre dell'est. 
^.^|4543 / -502		^.^|TLDNO				^.^|Si inizia a parlare di un potente drago bianco sulla cima dell'Elmo degli Dei
^.^|4560 / -485		^.^|TLDNO				^.^|Il Culto del Drago Bianco si diffonde a Meridia
^.^|4667 / -378		^.^|TLDNO				^.^|Nascono Vorth e Petri, figli della sorella dell'Imperatore, che vengono affidati a due famiglie nobili: i Maren ed i Vulic.
^.^|4669 / -376		^.^|TLDNO				^.^|Nasce Lorin Fernim, figlio dell'Imperatore di Meridia.
^.^|4697 / -348		^.^|TLDNO				^.^|Muore l'Imperatore. Disputa per la successione tra Vorth, Petri e Lorin. Vorth Maren e Petri Vulic ricevono le città di Staria ed Ederla
^.^|4698 / -347		^.^|TLDNO				^.^|Il barone Vorth Maren riceve l'immortalità da un diavolo da lui evocato.
^.^|4700 / -345		^.^|TLDNO				^.^|Una malattia sconosciuta inizia a mietere vittime a Meridia. Evasione di massa dalla Torre delle Catene. Norlyn chiude tutti gli accessi alla montagna.
^.^|4701 / -344		^.^|TLDNO				^.^|Tedara è assediata da Vorth l'Immortale, con un esercito di immondi. I malati iniziano ad essere deportati a Vagra.
^.^|4704 / -341		^.^|TLDNO				^.^|Tedara cade e diventa capitale del nuovo regno. Vorth si proclama dittatore. L'epidemia continua a flagellare l'isola di Meridia
^.^|4706 / -339		^.^|TLDNO				^.^|Il numero di nuovi infetti inizia a scendere. Primi insediamenti ad Ethedan e Sernost.
^.^|4707 / -338		^.^|TLDNO				^.^|Funzionari imperiali riferiscono di una repubblica nell'isola di Vagra. Azug ed Icta annesse al Ducato Vulic.
^.^|4709 / -336		^.^|TLDNO				^.^|L'epidemia è completamente scomparsa. La Gilda dei Mercanti del Mar d'Oro acquista le isole ad est di Meridia. Nasce la Confederazione Commerciale
^.^|4710 / -335		^.^|TLDNO				^.^|L'Impero concede alla città di Norlyn terre e sovranità in cambio di pace ed accordi commerciali. Viene fondata Cudir.
^.^|4712 / -333		^.^|TLDNO				^.^|Sindan è annessa al Ducato. Accordo di pace tra Impero e Ducato. Nasce Ladica Vulic. Accordi commerciali tra Impero e Confederazione.
^.^|4732 / -313		^.^|TLDNO				^.^|Ladica si ammala e viene deportata a Vagra ed il Ducato va a suo fratello.  Primi contatti con la Repubblica dei Senza Luce.
^.^|4735 / -311		^.^|TLDNO				^.^|Fondazione di Nagastan.
^.^|4735 / -306		^.^|TLDNO				^.^|Ladica entra a far parte del consiglio dei sette della Repubblica.
^.^|4830 / -216		^.^|TLDNO				^.^|Muore il governatore di Carelian. Iniza la ribellione. Il Mare di Vagra è infestato da pirati ribelli. Viene chiamato Mar dei Relitti.
^.^|4832 / -214		^.^|TLDNO				^.^|Carelian è assediata. L'esercito imperiale è attirato nella Barriera Verde e massacrato. I pirati razziano e bruciano la città di Ledel.
^.^|4958 / -87		^.^|TLDNO				^.^|Muore l'ultimo Duca Vulic, senza eredi. Il trono passa alla sua antenata, Ladica, della Repubblica dei Senza Luce.
^.^|4960 / -85		^.^|TLDNO				^.^|Apparizioni di non morti nelle isole della Confederazione Commerciale. Intere popolazioni delle isole del Mar d'Oro scompaiono. Ladica abbandona Ederla.
^.^|4961 / -84		^.^|TLDNO				^.^|Medor è attaccata da un'armata non-morta. La popolazione viene completamente spazzata via. Gli elfi della grande foresta impazziscono e si ribellano a Norlyn
^.^|4961 / -84		^.^|TLDNO				^.^|L'armata non-morta scompare improvvisamente. Le isole del Mar d'Oro tornano com'erano, tranne per la popolazione.
^.^|4970 / -75		^.^|TLDNO				^.^|Medor viene gradualmente ripopolata. La Confederazione Commerciale rinasce, con il nuovo nome di Gilda della Fenice.
^.^|4974 / -71		^.^|TLDNO				^.^|La scoperta di giacimenti di pietre e metalli preziosi favorisce il ripopolamento dell'arcipelago del Mar d'Oro. Fondazione di Nuova Ledel.
^.^|4980 / -65		^.^|TLDNO				^.^|Guerra fra la Gilda della Fenice e l'Impero di Meridia per il controllo del Mar d'Oro.
^.^|4996 / -49		^.^|TLDNO				^.^|La flotta imperiale viene definitivamente sconfitta al largo di Boria.
|===